### ISSUE TITLE
v0.81.0 | `Realm.Config` now returns `RealmConfigurationBase`

### ISSUE THREAD

**Issue by sushihangover** [realm/realm-dotnet#1032]
#### Goal

Retrieve a `RealmConfiguration` from a current Realm Instance

#### Expected Results

A object of type `RealmConfiguration`

#### Actual Results

A `RealmConfigurationBase` is returned

#### Steps & Code to Reproduce

Create a class that accepts a `RealmConfiguration` param

	public class TestClass
	{
		public TestClass(RealmConfiguration config)
		{
		}
	}

#### Code Sample

	using (var realm = Realm.GetInstance("081.db"))
	{
		var foo = new TestClass(realm.Config);
	}

>Error CS1503: Argument `#1' cannot convert `Realms.RealmConfigurationBase' expression to type `Realms.RealmConfiguration' (CS1503) (Realm081Test.iOS)

#### Version of Realm and tooling
Realm version(s): 0.81.0
Which operating system version and device: iOS,  Android, and Forms

**Comment by nirinchev** [comment]
Hi @sushihangover. The reason we're adding an extra parent class is because we're gearing up for supporting an additional configuration type (`SyncConfiguration`). While this release doesn't include sync, we thought we could still include the modified inheritance chain as a preparation for that.

However, it is definitely an omission on our part for not explicitly stating it in the release notes. For now, it would be safe to cast `realm.Config` to `RealmConfiguration`, but that would be fragile if people used `SyncConfiguration` from a future release. Is there a particular reason why your method needs a `RealmConfiguration` instance or can it work with a `RealmConfigurationBase`? As you've probably noticed, we changed our API to accept `RealmConfigurationBase` wherever we would use `RealmConfiguration` before that, so probably just a change of the argument type would be sufficient for your case?

**Comment by sushihangover** [comment]
@nirinchev Thanks for the info. 

I reported it since it is a breaking API change in multiple projects across a number of apps and was not clear if using `RealmConfigurationBase ` was acceptable/OK as `0.81.0` is now causing `SIGABRT`  across the first two apps that I tried upgrading. 

Since this is not an issue, I'll work on finding the cause root of the native `libc++abi.dylib` exceptions that 0.81.0 is causing if the client wishes to proceed w/ the update. Thanks again.

**Comment by nirinchev** [comment]
Those crashes are definitely not something we'd expect/encountered after updating our internal projects. We'd be happy to help investigate those if you have permission to share the project/can create an isolated repro.

**Comment by sushihangover** [comment]
@nirinchev Thanks for the quick reply and the offer... I'll pass the offer along to the client with your contact info, but *usually* the reply is no as they are very protective of their IP and also not allowing access from out of the country (USA) due to possible public medical disclosures if a security breach happens, etc, etc..... 👮

**Comment by fealebenpae** [comment]
@sushihangover a crash log or at least the stacktrace could help us determine what the issue might be or if it's Realm-related.

**Comment by sushihangover** [comment]
I am going to close this as my issue/question concerning `RealmConfiguration` vs. `RealmConfigurationBase` was answered and converting the code to use `...Base` works fine. 

If the client goes a thumbs up to continue working on the native crash issue, I'll open another issue. Thanks.
