### ISSUE TITLE
The Realm is already in a write transaction

### ISSUE THREAD

**Issue by RickTheHat** [realm/realm-dotnet#1056]
Using Xamarin Studio and calling an API with approx 1k of json data and when realm table is empty, it loads properly.

The problem I'm having is when I hit the "refresh" button in my app, it's supposed to update & add new records with the latest API json data which it does first time but if I try a third time, I will get this error "The Realm is already in a write transaction".

```
// get instance of realm db
var realm = Realm.GetInstance("/Users/ME/Desktop/myDB.realm");

using (var trans = realm.BeginWrite())
{
    foreach (var item in items) <-- items is my json data from API
    {
        var entry = new realmWidget();

	entry.Id = item.Id; <-- in my model I am using [PrimaryKey]
	entry.Title = item.Title;
	entry.LoadedOn = DateTimeOffset.UtcNow;

	realm.Add(entry, true);
    }
    trans.Commit();
}
```

**Comment by AndyDentFree** [comment]
@RickTheHat can you please supply more context for exactly how this method is being invoked. Is it on a background thread or in an async button handler?

**Comment by RickTheHat** [comment]
hi andy, first of all, LOVE  this DB. so much nicer then sqlite IMO

let me play with this a bit more tonight as I feel like I'm close to a solution. I do notice that I have two realm instances open at the same time, one to query and one to add/update the table and maybe that is causing a problem?!?

the workflow when onload of a screen of my xamarin app --> i call the method below and if 0 records exist, i make an api call to get the data and load it up in the AddOrUpdateToRealmTable which has the code aboce OR  if the user clicks a refresh button, i make the same method call to get the data and load it up and of course, if records exist, I skip all that and ToList() and return existing data.

```
public async Task<List<RealmTable>> GetItems(SortType sort, bool forceRefresh = false)
{
	var realm = Realm.GetInstance("/Users/ME/Desktop/myDB.realm");
	var qry = realm.All<RealmTable>();

	if (qry.Count() == 0 || forceRefresh)
	{
		// rest url
		var _url = "";
		
		// use refit to make api calls
		var externalApi = RestService.For<IApi>(_url);
		var items = await externalApi.GetItems(); <== returns json from api

		AddOrUpdateToRealmTable(items); <== in this method I call another Realm.GetInstance to add/update

		qry = realm.All<RealmTable>(); <== get latest records from previous line of code
	}

	return qry.ToList();
)
```

**Comment by AndyDentFree** [comment]
@RickTheHat we're kinda fond of it too.

> I do notice that I have two realm instances open at the same time, one to query and one to add/update the table 

Opening multiple instances should never be a problem, especially in the same thread. The only problem is if you use a reference from one and pass it into an async process - it will not be valid on the other thread. Similarly if you **return a RealmObject** from an async call - it's almost always coming from another thread.

I think you have fallen into this trap here - looking at your last line `return qry.ToList();` you are returning a list of RealmObjects back across a thread boundary, from a Realm instance that is going to get cleaned up.

So, I would return a bool indicating you need to refresh the list then do `realm.All<RealmTable>()` in the caller.

**Comment by nirinchev** [comment]
There are a few points I'd like to clear up.

It is very unlikely that you're hitting threading issues here. The reason is that unless you mess with the `SynchronizationContext` or call `ConfigureAwait(false)` on your tasks, `await`-ed tasks will return on the same thread (in Xamarin projects). Therefore, you're most likely not passing objects across thread boundaries. Additionally, `RealmObject`s hold reference to their `Realm`, so even though your `realm` variable goes out of scope at the end of your method, the instance should be kept alive until all objects are eligible for collection. The fact that you're able to perform a few updates prove that passing objects across threads is not the culprit here (if that were the case, it would fail every time).

Now, back to your original question - as Andy said, opening multiple instances on the same thread *should* not be an issue. However, starting multiple write transactions on the same thread, even if on different Realm instances, *is* an issue, which is what I'm guessing is happening here. To try and debug that, I would do something like:

```csharp
var transId = Guid.NewGuid();
Console.WriteLine($"Starting: {transId} on thread {Thread.CurrentThread.ManagedThreadId}");
var transaction = realm.BeginWrite();
/* perform updates */
transaction.Commit();
Console.WriteLine($"Finished: {transId} on thread {Thread.CurrentThread.ManagedThreadId}");
```
wherever you have doubts that there might be simultaneous updates happening. In non-crashing scenarios, you'll have couples of `Starting: XYZ on thread N`, `Finished: XYZ on thread N`. In your case, I expect that you'll see `Starting: XYZ on thread N`, `Starting: ABC on thread N` followed by a crash.

**Comment by AndyDentFree** [comment]
Hi @RickTheHat sorry for the threading scare which my colleague corrected - I have gone and re-read [There is no Thread](http://blog.stephencleary.com/2013/11/there-is-no-thread.html) to remind myself that async != thread.

We had a similar issue with #851 where it seemed that data binding to a list was causing the problem. it would be very helpful if you can provide a stack trace or send a runnable project to support@realm.io.

**Comment by RickTheHat** [comment]
I'm still moving pieces around to see if it's how I'm architecting the calls so stay tuned...

**Comment by RickTheHat** [comment]
I was able to figure this out and will post how I did it in a github example project. Thanks for all the help.

**Comment by nirinchev** [comment]
Glad to hear that! Looking forward to the example :)
