### ISSUE TITLE
Indexed searching speed

### ISSUE THREAD

**Issue by AmrTealeb** [realm/realm-dotnet#1069]
I am using Realm to store data on mobile device using Xamarin android.
I use this class to store data.
```csharp

 public class Location : RealmObject
    {     
        [PrimaryKey]
        public int Id { get; set; }

       [Indexed]
        public string Name { get; set; }

        public float Latitude { get; set; }

     public float Longitude { get; set; }

       [Indexed]
      public string CountryCode { get; set; }

        public bool IsCountry { get; set; }
    }
```

And i search using this code :

```csharp
 public List<Location> SearchExact(Realm realm, string text, int limit = 20)
        {
            try
            {
                Func<Location, bool> f = x => x.Name.Equals(text, StringComparison.OrdinalIgnoreCase);                
                var matched = realm.All<Location>().Where(f).Take(limit).ToList();
                return matched;                
            }
            catch (Exception ex)
            {
                return new List<Location>;
            }
        }

```
The search is so slow when the realm db contains more than 100,000 records. it takes more than 2 minute to search for a location by name.
I this the correct way to search for indexed properties?

**Comment by fealebenpae** [comment]
Hi @AmrTealeb,

The type of `f` needs to be `System.Linq.Expressions.Expression<Func<Location, bool>>`. You can use the same declaration, just change the type of the variable.

This is because Realm is a LINQ provider and needs a query described by an `Expression` object which it can parse at runtime and efficiently execute. The difference between `Func` and `Expression<Func>` is that the former is a compiled method, while the latter is a syntax tree that describes the method.

As it is right now, the query has to execute the method `f` for every `Location` object in the database as if it was a regular object in memory instead of being able to take advantage of the query engine in Realm. Please change the type of `f` to make it an `Expression` and try again.

**Comment by AmrTealeb** [comment]
Hi @fealebenpae,

Thank you very much for your help.
this works now and very fast
```csharp
System.Linq.Expressions.Expression<Func<Location, bool>> f = 
           x => x.Name.Equals(text,StringComparison.OrdinalIgnoreCase);
var matched = realm.All<Location>().Where(f).ToList();
```
and this too
```csharp
System.Linq.Expressions.Expression<Func<Location, bool>> f = 
                    x => x.Name.Contains(text);
var matched = realm.All<Location>().Where(f).ToList();

```

**Comment by nirinchev** [comment]
Glad to hear that :) Also, keep in mind that you can supply the lambda directly to the `.Where` clause to avoid the lengthy variable declaration:

```csharp
var matched = realm.All<Location>()
                   .Where(l => l.Name.Contains(text, StringComparison.OrdinalIgnoreCase))
                   .ToList();
```

The compiler will correctly infer the type of the lambda as an `Expression<Func<Location, bool>>`, so performance will be unaffected.

I'll be closing that issue, but if you have any further questions or concerns, feel free to reopen it or create a new one.
