### ISSUE TITLE
RealmConfiguration doc page fails to appear (was Broken link in Class Subsets)

### ISSUE THREAD

**Issue by istx25** [realm/realm-dotnet#1160]
There is a broken link in the documentation. You can reproduce the issue by going to https://realm.io/docs/xamarin/latest/#class-subsets and clicking on "RealmConfiguration" in _You can do this by setting the ObjectClasses property of your **RealmConfiguration**_. Originally reported via email.

**Comment by AndyDentFree** [comment]
Sigh, this is something utterly weird in the **publishing** side - we generate a completely legal page and something about its content causes it to not get delivered. You can see the original page [as uploaded](https://github.com/realm/realm.io/blob/master/source/en/docs/xamarin/latest/api/class_realms_1_1_realm_configuration.html). 

The same page is linked in the automatically generated links on the [API home](https://realm.io/docs/xamarin/0.81.0/api/)

We are moving to a completely different API documentation system which should stop this happening again. It was finished in issue #1074 but a new copy has yet to be deployed as there have been no releases since.

**Comment by istx25** [comment]
Sounds good, @AndyDentFree. Thank you for getting back to me. I'll follow-up with the user who reported the issue via email. :-)

**Comment by nirinchev** [comment]
That being said, we should make sure to update all the references to the new format.  I created #1161 to keep track of that.

**Comment by istx25** [comment]
The user who reported the original broken link in this issue reported another. https://realm.io/docs/xamarin/latest/api/class_realms_1_1_realm_list-members.html

**Comment by nirinchev** [comment]
Those all should be fixed once we move to docfx. I'll be closing this now, as we don't have plans to fix the existing api reference documentation.
