### ISSUE TITLE
WriteAsync doesn't advance the read transaction

### ISSUE THREAD

**Issue by hrach** [realm/realm-dotnet#1192]
After a successful WriteAsync, the data fetched from another realm are not correctly updated with the last update. Let's have the following pseudocode:

```cs
var realm1 = Realm.GetInstance();
await realm1.WriteAsync((innerRealm) =>
{ 
     var book = innerRealm.Find<Book>(1);
     book.published = true;
});

var realm2 = Realm.GetInstance();
var book = realm.Find<Book>(1);
book.published; // false
```

If I put in between some sleep, it works. Am I missing something?

**Comment by fealebenpae** [comment]
There are two things to note here:
1) Calling `GetInstance()` on the same thread with the same arguments is going to give you the same realm underneath. You can check this by calling `realm2.IsSameInstance(realm1)`.
2) When performing writes on another thread, the realm instance on the current thread is automatically updated only on the next even loop tick, or when you manually call `Refresh()`.

This means that `WriteAsync` does persist the data to disk, but the realm instance you call `WriteAsync` on is not yet notified of this. Even though you call `Realm.GetInstance()` again, because of the caching mechanism you get `realm1` and because it hasn't been notified yet by the event loop it still points to the previous version of the data - `var realm2 = Realm.GetInstance()` doesn't give you a fresh view of the realm file.

If you need to access the changed data immediately after awaiting `WriteAsync`, call `Refresh` on the realm. In fact, it seems to me that `WriteAsync` should call `Refresh` internally as that behavior might be more intuitive.
