### ISSUE TITLE
Win32 wrappers not available when downloading NuGet

### ISSUE THREAD

**Issue by jonstodle** [realm/realm-dotnet#1239]
#### Goal

Run realm as part of a WPF app, targeting .Net 4.5.2

#### Expected Results

To build

#### Actual Results

It doesn't build claiming the Win32 wrapper dlls are unavailable: `C:\Dev\AdGroupSearch\packages\Realm.1.0.3\native\win32\x86\realm-wrappers.dll" because it was not found.` and `C:\Dev\AdGroupSearch\packages\Realm.1.0.3\native\win32\x64\realm-wrappers.dll" because it was not found.`

Checking in the `C:\Dev\AdGroupSearch\packages\Realm.1.0.3\native` folder, there's only an `android` and an `iOS` folder present.

#### Steps & Code to Reproduce

The following has been tried to resolve:

* Remove Nuget packages and re-add them
* Remove package folders in `C:\Dev\AdGroupSearch\packages` and restore packages
* Download Nugets using both VS 2015 and VS2017RC
* Download Nuget in Linqpad and test there, but same error

#### Code Sample

```csharp

// N/A

```

#### Version of Realm and tooling
Realm version(s): 1.0.3

Xamarin/Visual Studio version: VS2017RC mainly, but also tried VS2015

Which operating system version and device: Windows 10 Enterprise 1607 targeting .Net 4.5.2

**Comment by fealebenpae** [comment]
Hi @jostodle,

I just checked and this is a bug - the workaround is to only add the `Realm.Database` NuGet package to your project.

The `Realm` package contains the Realm Mobile Platform APIs and layers on top of `Realm.Database`. Since the RMP is not supported on Windows just yet, you can safely reference only `Realm.Database` in your WPF project.

**Comment by mzimdars-gms-online-de** [comment]
is it correct that it means that sync'ing is not supported currently on .Net Windows Desktop?
Then I have a question and a comment:
Q: Is there a date when it will be available?
C: It is not visible from your documentation anywhere, that the feature set between platforms is different. it would be nice to have such a 'feature matrix'. Otherwise, it leads to disappointment if it looks like it is available, but then you cannot use it.

**Comment by fealebenpae** [comment]
@mzimdars-gms-online-de, you are correct - sync features are not available on Windows right now. We're in the process of updating our documentation to reflect this and other current limitations in the 1.0 release - right now this is only described in our [release blogpost](https://realm.io/news/realm-microsoft-xamarin-1-0-azure-windows-desktop/).

I cannot say when we'll have sync on Windows platforms, but it's high on our list of priorities and one of the immediate next tasks for the team.

**Comment by nirinchev** [comment]
We have had a warning in the [Sync section](https://realm.io/docs/xamarin/latest/#enabling-realm-mobile-platform), but it's not very prominent. I've updated our current limitations section to include more details for Windows Desktop limitations: https://realm.io/docs/xamarin/latest/#limitations-on-windows-desktop.
