### ISSUE TITLE
Outofmemoryexception when compiling the Journal example out of the box

### ISSUE THREAD

**Issue by SaigueFault** [realm/realm-dotnet#1341]
I am having trouble at getting the example "QuickJournal" to compile on iOS. The code compiles OK, but fails during the Fody step. I posted this on StackOverflow but was redirected here

The compilation fails with a Macbook Air Early 2014 with the latest MacOS/Visual Studio Mac
Steps taken to try and solve the issue:
- Restart the mac and try to compile with nothing else running (1.7GB available physical memory + cache)

## Goals

Try out the example application for .NET through the following
- Pull the repository
- Open the solution in examples/QuickJournal
- Compile and test

## Expected Results

Smooth compilation & testing experience

## Actual Results

Fody out of memory exception

## Steps to Reproduce

See the setup, follow steps
I am using the latest Xamarin/Visual Studio Mac/XCode

## Code Sample

The regular realm source code

## Version of Realm and Tooling

git clone https://github.com/realm/realm-dotnet.git
 
git checkout 8f5e36ffd91e06b9c60b91f9de3fb312b411a4a4

The exception I am getting is       
Fody: Found debug symbols at '~/realm-dotnet/examples/QuickJournal/QuickJournal/obj/Debug/QuickJournal.pdb'.
    MSBUILD : error : Fody: An unhandled exception occurred:
    MSBUILD : error : Exception:
    MSBUILD : error : Out of memory
    MSBUILD : error : StackTrace:
    MSBUILD : error :   at (wrapper alloc) System.Object:AllocVector (intptr,intptr)
    MSBUILD : error :   at Microsoft.Cci.Pdb.MsfDirectory..ctor (Microsoft.Cci.Pdb.PdbReader reader, 

See log file
[RealmCompilelog.txt](https://github.com/realm/realm-dotnet/files/906913/RealmCompilelog.txt)

**Comment by nirinchev** [comment]
Looks like that's an issue with Fody - there are a few similar issues in other Fody-dependendent repositories. A brief search turned up this NuGet package: https://www.nuget.org/packages/Hotfix.Fody.Pdb/. 

I can't say whether it will work or not because all machines I have laying around are with 8/16 GB ram and those compile just fine, but feel free to give it a try. The underlying cause seems to be Cecil which loads the entire assembly, along with the debug symbols in memory - https://github.com/jbevain/cecil/pull/271.

**Comment by SaigueFault** [comment]
I did install the hotfix, however it caused fody to fail with the same error as in 
https://github.com/realm/realm-dotnet/issues/1309

I can do further testing if required, however I'll wait until I can test it on my main machine for now.
