### ISSUE TITLE
Manually use OnPropertyChanged and trigger PropertyChanged?

### ISSUE THREAD

**Issue by EmmanVazz** [realm/realm-dotnet#1460]
Is it possible to have OnPropertyChanged calls in the RealmObject model for variables that just have getters included in the PropertyChanged event?
 
I forked the realm example here https://github.com/EmmanVazz/realm-dotnet/tree/master/examples/QuickJournal . As you can see I am trying to trigger OnPropertyChanged for Random in the setter for BodyValue. However if you look at the print statements for when an object is saved it doesn't show Random. 

This is the code of what I am doing in my real project. The PropertyChanged Event only sends the names of the individual arrays that were changed but not the Children property name.

```
public IList<INode> Children
{
	get
	{
		var children = new List<INode>();
		children.AddRange(Articles);
		children.AddRange(Audios);
		children.AddRange(Photos);
		children.AddRange(Social_Medias);
		children.AddRange(Texts);
		children.AddRange(Videos);
		children.AddRange(Events);
		children.AddRange(Locations);
		children.AddRange(Products);
		children.AddRange(Containers);
		return children.OrderBy(c => c.Sort).ToList();
	}
}

private IList<Article> Articles { get; }
private IList<Audio> Audios { get; }
private IList<Photo> Photos { get; }
private IList<Social_Media> Social_Medias { get; }
private IList<Text> Texts { get; }
private IList<Video> Videos { get; }
public IList<Event> Events { get; }
public IList<Location> Locations { get; }
public IList<Product> Products { get; }
public IList<Container> Containers { get; }


private void PopulateChildren(IList<INode> children)
{
	if (!Children.OrderBy(c => c.Sort).SequenceEqual(children.OrderBy(c => c.Sort), new ViewINodeEqualityComparer()) || children.Where(x => x.HasChanged).Any())
	{
		Articles.Clear();
		Audios.Clear();
		Photos.Clear();
		Social_Medias.Clear();
		Texts.Clear();
		Videos.Clear();
		Events.Clear();
		Locations.Clear();
		Products.Clear();
		Containers.Clear();

		foreach (var child in children)
		{
			if (child.HasChanged)
				child.HasChanged = false;

			if (child.GetType() == typeof(Article))
				Articles.Add((Article)child);
			else if (child.GetType() == typeof(Audio))
				Audios.Add((Audio)child);
			else if (child.GetType() == typeof(Photo))
				Photos.Add((Photo)child);
			else if (child.GetType() == typeof(Social_Media))
				Social_Medias.Add((Social_Media)child);
			else if (child.GetType() == typeof(Text))
				Texts.Add((Text)child);
			else if (child.GetType() == typeof(Video))
				Videos.Add((Video)child);
			else if (child.GetType() == typeof(Event))
				Events.Add((Event)child);
			else if (child.GetType() == typeof(Location))
				Locations.Add((Location)child);
			else if (child.GetType() == typeof(Product))
				Products.Add((Product)child);
			else if (child.GetType() == typeof(Container))
				Containers.Add((Container)child);
		}

		OnPropertyChanged(nameof(Children));
	}
}
```

Any idea?

**Comment by EmmanVazz** [comment]
Changing OnPropertyChanged calls to RaisePropertyChanged calls fixes the example project, However my real project still doesn't fire off PropertyChanged for Children.

**Comment by EmmanVazz** [comment]
Okay I reproduced my issue with the sample project again, it is at the same URL. It seems like the issues is that I am doing the write in a worker thread and that RaisePropertyChange doesn't surface to the UI thread. Maybe we need a way to manually add a property to the change list for the NotifyCallbacks so that gets fired on the UI thread like the other properties.

**Comment by nirinchev** [comment]
There are several issues with the approach shown in your project. The reason you're not seeing notifications is not because it's operating on a background thread, but rather because you're raising them at another instance. To try and illustrate:

```csharp
RealmObject = _realm.All<JournalView>().FirstOrDefault(); // First instance
RealmObject.PropertyChanged += RealmObject_PropertyChanged; // Subscribe to RealmObject's property changed event

// Later on
// I'm breaking down realm.All<JournalView>().First().AddEntry(entry); for clarity
var tempObject = realm.All<JournalView>().First(); // A different instance from RealmObject
tempObject.AddEntry(entry); // PropertyChanged is raised for tempObject but not RealmObject because they are different instances
```

You should instead subscribe to the `CollectionChanged` event of the `Entries` property:

```csharp
RealmObject.Entries.AsRealmCollection().CollectionChanged += (s, e) =>
{
    ProcessChildren();
};
```

In general, objects are not supposed to raise PropertyChanged for collection properties, especially with Realm, because those are never changed - adding or removing objects doesn't change the collection itself. Instead, these collections should implement `INotifyCollectionChanged` and raise collection notifications when items are added or removed.

I hope this helps, if you have further questions, don't hesitate to ask us.

**Comment by EmmanVazz** [comment]
Ah that clears stuff up more. I want to manually trigger an event to let subscribers know that the list of children has changed. As you can see Children is a group of realm collection and I can't cast that to a RealmCollection.  I also rather not subscribe to the individual realm collections as I have interfaces and definitions of Children vary. However it seems like you guys already have a mechanism to fire off the RaisePropertyChanged on the right thread, [here](https://github.com/realm/realm-dotnet/blob/0d8792a7f96c54cbb36a6bf21279dec3ae59d1e9/Realm/Realm/RealmObject.cs#L717). Would there be any way to manually add a propertyName in the changes parameter? Otherwise how you would do something like what I am shooting for.

**Comment by nirinchev** [comment]
To me it seems like you need something like WPF's CompositeCollection? Unfortunately, that doesn't seem to be available for Xamarin.Forms, but you can take inspiration from [this Stack Overflow thread](https://stackoverflow.com/questions/13203795/binding-multiple-observablecollections-to-one-observablecollection/13205040#13205040) to implement your own.

Because those `IList` properties are persisted in Realm, you can subscribe to `CollectionChanged` and use that to trigger parent notifications. The easiest approach would be to always trigger `Reset` whenever a child collection changes (which will effectively be the same as raising `PropertyChanged` for the property), and with some basic index algebra, you can actually calculate the parent changes and raise precise notifications.
