### ISSUE TITLE
Better runtime error message when schema contains duplicate class names

### ISSUE THREAD

**Issue by amasasi** [realm/realm-dotnet#1463]
I get the ITem is already added exception for a newly created database'
[Bug_Repro.zip](https://github.com/realm/realm-dotnet/files/1102754/Bug_Repro.zip)

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by fealebenpae** [comment]
This means you have two or more `RealmObject` classes with the same name. Searching through the project you shared I can find that there are two `Project` classes - one in `MobileDataKit.Core.Shared/Model/Project.cs` and one in `MobileDataKit_Collect/MobileDataKit_Collect/MobileDataKit_Collect/Model/Project.cs`. Normally this would be a build error if the two classes were in the same assembly, but they seem to be separate in this case. We should improve the runtime error message because right now that's just the Dictionary.Add method throwing an exception.

To get around this you need to either remove or rename one of the classes, or explicitly pass in a Type array where the class names are unique in `RealmConfiguration.ObjectClasses` when creating your realm instance.

**Comment by amasasi** [comment]
This saved my day, thank you so much.

 However MobileDataKit.Core.Shared is a shared project which means technically they are in the same project, am  i missing something?

**Comment by fealebenpae** [comment]
It's a different class with the same name. Even its members are different between the two definitions.
