### ISSUE TITLE
[Feature] AutoIncrement for int PrimaryKey

### ISSUE THREAD

**Issue by listepo-alterpost** [realm/realm-dotnet#1735]
It would be great to have
```C#
    public class Employee : IEmployee
    {
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }

        public string Name { get; set; }

        public int Age { get; set; }

        public bool IsHired { get; set; }  
    }
```
https://github.com/realm/realm-dotnet/blob/5ac65fa373e777cb4af6c1f5b2e5c3e069427244/examples/Benchmarkr/SQLite/Employee.cs#L26

**Comment by nirinchev** [comment]
Thanks for the suggestion but auto incrementing keys is something we intentionally do not support. The reason is that Realm is designed to be a synchronized database and generating such keys in distributed environment is unfeasible. There's a section in the java docs that provides a more in-depth motivation: https://realm.io/docs/java/latest/#auto-incrementing-ids.

**Comment by listepo-alterpost** [comment]
@nirinchev thanks, understood. Do you plan to support GUID as binary type? or .net type GUID for RealmObject?
