### ISSUE TITLE
User.ApplyPermissionsAsync task never completes but does apply permissions running on .Net Core

### ISSUE THREAD

**Issue by ahdata** [realm/realm-dotnet#1764]
## Goals
Add permissions to a realm synchronously from a server running .Net.

## Expected Results
The async task should complete

## Actual Results
The Task never returns.

## Steps to Reproduce
Create an ASP.NET Core Web Application (targeting core 2.1) (api project)
Add the Realm nuget package. (version 3.1.0)
Create a Controller that sets permissions for already created users and realm
```csharp
        [HttpGet]
        public async Task<IActionResult> AddPermissionToRealm()
        {
            var authURL = new Uri($"https://{REALM_HOST}");
            //two users have already been created 
            var adminCredentials = Credentials.UsernamePassword("test-admin", "tacos1", false);//admin
            var basicCredentials = Credentials.UsernamePassword("test-user", "tacos2", false);//regular user
            var admin = Realms.Sync.User.LoginAsync(adminCredentials, authURL).Result;
            var basic = Realms.Sync.User.LoginAsync(basicCredentials, authURL).Result;

            //lets give "basic" access to this realm
            var realmString = $"/orgs/unique-organization";

            //create the realm with admin user
            var serverURL = new Uri(realmString, UriKind.Relative);

            var condition = PermissionCondition.UserId(basic.Identity);
            //hangs waiting on this line.
            await admin.ApplyPermissionsAsync(condition, realmString, AccessLevel.Write);
            return new OkObjectResult(new { });
        }
```

## Possible Reason Why
It looks like ApplyPermissionsAsync waits for an event to fire and it never fires at line 72. [UserPermissionsExtensions.cs](https://github.com/realm/realm-dotnet/blob/7556567671ece1ef99aa12aa70bf43ad35c9d07c/Realm/Realm.Sync/Permissions/UserPermissionsExtensions.cs)

## Version of Realm and Tooling

- Realm Object Server Version: 3.9.11 running on Realm Cloud

- Server OS & Version: Running in Visual Studio on Windows 10

**Comment by nirinchev** [comment]
The most likely reason why this happens is because `ApplyPermissionsAsync` relies on a Realm notification to be delivered, but these are only delivered on threads with synchronization context. In ASP.NET, the controllers run on threadpool threads, which by default don't have synchronization context, meaning that the notification will never be delivered (as you've correctly narrowed it down to that handler).

There are several workarounds for this, but the most straightforward one is to use a package like [Nito.AsyncEx.Context](https://www.nuget.org/packages/Nito.AsyncEx.Context) that will install a synchronizationcontext on your thread. Then you'll need to do a trivial modification to your controller to make it work:

```csharp
[HttpGet]
public IActionResult AddPermissionToRealm()
{
    AsyncContext.Run(async () =>
    {
        // ... stuff
        await admin.ApplyPermissionsAsync(condition, realmString, AccessLevel.Write);
    });
    return new OkObjectResult(new { });
}
```

**Comment by nirinchev** [comment]
Glad to hear that!
