### ISSUE TITLE
Realm.DeleteRealm throwing Realms.Exceptions.RealmPermissionDeniedException even when disposed

### ISSUE THREAD

**Issue by brittonbeckham** [realm/realm-dotnet#1773]
## Goals
Delete the Realm.

## Expected Results
The Realm deletes without throwing an exception.

## Actual Results
After calling `Realm.GetInstance(config).Dispose()`, I call `Realm.DeleteRealm(config)` which throws an exception `Realms.Exceptions.RealmPermissionDeniedException: Unable to delete Realm because it is still open.` Upon inspection of the instance realm via the debugger, `LocalStorage.IsClosed` is still false after calling `Dispose()`.

Something to note: This code has remained unchanged and has worked for nearly 2 years without issue, but upon upgrading to `Realm.Database` 3.2, I started seeing this issue.

## Steps to Reproduce
See above.

## Code Sample
```c
private Realm LocalStorage => Realm.GetInstance(GetRealmConfig());

public void Delete()
{
	App.Log.Info("Deleting realm.");

	//delete data on device (realm)
	if (_config != null)
	{
		LocalStorage.Dispose();
		Realm.DeleteRealm(_config); //throws exception here,crashing app; 
		App.Log.Info("Realm deleted.");
	}
	
	//clear local db identifier (this will force app to generate a new realm)
	_localDbId = null;
	_appIo.SetPreference(AppPreference.DbIdentifier, null);
	_appIo.SetPreference(AppPreference.DbSchemaVersion, null);
	_config = null;
}

private RealmConfiguration GetRealmConfig()
{
	return _config ?? (_config = BuildRealmConfig());
}

private RealmConfiguration BuildRealmConfig()
{
	var dbId = GetLocalDbId();
	var dbName = $"prepify-{App.User.MemberInfo.MemberGuid}_{dbId}.realm";
	var schema = GetSchemaVersion();
	App.Log.Info($"Access realm: schema {schema} | id {dbId} | name {dbName}");

	return new RealmConfiguration(dbName)
	{
		ShouldDeleteIfMigrationNeeded = true,
		SchemaVersion = schema
	};
}

private ulong GetSchemaVersion()
{
	return _appIo.GetPreference<ulong?>(AppPreference.DbSchemaVersion) ?? 1;
}

private int GetLocalDbId()
{
	App.Log.Info($"getting dbId");

	lock (_locker)
	{
		if (!_localDbId.HasValue)
			_localDbId = _appIo.GetPreference<int?>(AppPreference.DbIdentifier);

		if (!_localDbId.HasValue)
		{
			_localDbId = new Random(DateTime.Now.Millisecond).Next(111111, 999999);
			App.Log.Info($"set new dbId {_localDbId}; this will force generate a new realm when accessed");
			_appIo.SetPreference(AppPreference.DbIdentifier, _localDbId);
		}
	}

	return _localDbId.Value;
}
```

## Version of Realm and Tooling
* Realm Object Server Version: n/a
* Flavor:
  * [ ] Developer
  * [ ] Professional
  * [ ] Enterprise
* Server OS & Version: ? n/a
* Client SDK Version: Realm.Database 3.2
* Client OS & Version: iOS 11.4; NET Standard 2.0; XF 3.2

**Comment by nirinchev** [comment]
Which version of Realm did you upgrade from?

**Comment by brittonbeckham** [comment]
Looks like I was on 1.4.

**Comment by brittonbeckham** [comment]
Forgot to mention this is happening on both Android and iOS,

**Comment by IngweLand** [comment]
Still happening with the latest version as for now.

**Comment by JonathanImperato** [comment]
+1
Still happening on version 4.3.0

**Comment by DominicFrei** [comment]
The above mentioned switch from `1.4` to `3.2` had indeed changes in the `DeleteRealm` functions:
https://github.com/realm/realm-dotnet/blob/1.4.0/Realm/Realm/Realm.cs#L158-L177
https://github.com/realm/realm-dotnet/blob/3.2.0/Realm/Realm/Realm.cs#L158-L181

Especially the also mentioned `RealmPermissionDeniedException` was also introduced between those two versions. So seeing it in `3.2` but not in `1.4` makes sense. The check for an open Realm did not exist in `1.4`.

Interestingly enough this very scenario has been tested since (and before) version `1.4` already:
https://github.com/realm/realm-dotnet/blob/1.4.0/Tests/Tests.Shared/InstanceTests.cs#L70-L84

Looking further into `DeleteRealm` we're checking against the `_states` (https://github.com/realm/realm-dotnet/blob/master/Realm/Realm/Realm.cs#L200-L205) which is only updated in `Dispose`:
https://github.com/realm/realm-dotnet/blob/master/Realm/Realm/Realm.cs#L387-L390
- `Config.EnableCache` is only ever false within a migration for the `oldRealm` (https://github.com/realm/realm-dotnet/blob/master/Realm/Realm/Handles/SharedRealmHandle.cs#L525).
- `SharedRealmHandle.CanCache` is only ever false when using a `UnownedRealmHandle` during a migration (https://github.com/realm/realm-dotnet/blob/master/Realm/Realm/Handles/SharedRealmHandle.cs#L527).
- `_state.RemoveRealm(this)` can be false if there are `_weakRealms` left in https://github.com/realm/realm-dotnet/blob/master/Realm/Realm/Realm.cs#L1484

Most likely that Realm is still accessed somewhere else. I cannot judge this from the code sample alone.

@brittonbeckham @IngweLand I know you're posts have been quite a while ago but in case this issue still exists, would you be able to elaborate? Specifically if there are other processes / threads running at the same time that might be accessing this Realm as well.

**Comment by FoggyFinder** [comment]
got this exception on recent version. I have suspicion it happened because my system was heavily loaded with other processes.

**Comment by nirinchev** [comment]
If you're using Atlas Device Sync, this behavior is expected since releasing the file is an async operation that may complete after the Dispose call completed. If you're not using ADS and want us to look at it, please file a new issue and fill out the template.
