### ISSUE TITLE
Support "diffing object updates"

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-dotnet#1784]
See Java's implementation here: https://github.com/realm/realm-java/pull/6224
Related Epic: https://github.com/realm/realm-object-store/issues/697

**Comment by roberhofer** [comment]
@nirinchev : here is the ticket for the diffing capability.

**Comment by nirinchev** [comment]
This is going to be very hard to implement in .NET. The reason is that we don't use the object accessor API and it will be incredibly cumbersome and performance detrimental to start using it. It also is less of an issue compared to Java because in .NET we don't expose a mechanism to create an unmanaged object from a Realm object, which means that users are less likely to abuse the API and create a lot of churn by continuously copying objects in and out of Realm.

**Comment by fealebenpae** [comment]
For what it's worth I think we can implement this somewhat efficiently by weaving extra methods on `IRealmObjectHelper`, but it's gonna be a lot of work to pull it off and right now I don't think there's a lot of demand for diffed updates in .NET, like @nirinchev said.

**Comment by roberhofer** [comment]
The main driver for including .NET for diffing support was for completeness across the different bindings. 
For Java and iOS we had customers who did run into issues where this would have helped. 
Agree though that we do not have a specific customer as proof point where this is a issue. 
Thus given your argument above it's ok to punt on this. 
cc: @bmunkholm : Leave in Idea Backlog, or simply close as 'won't fix'?

**Comment by bmunkholm** [comment]
Let's close this as we don't intend to do it for now.
