### ISSUE TITLE
No ability to filter between dates using "Filter" method and keyword "BETWEEN"

### ISSUE THREAD

**Issue by ukushu** [realm/realm-dotnet#1817]
.Net realization of Filter have only one input parameter - string predicate. 
In case of another languages it's possible to use additional parameters to modificate predicate string.

Example:

_db.Realm.All<HistoryItem>().Filter("DoneTime BETWEEN {%@, %@}", date1, date2);

it's impossible to do in .NET family language;

And no, using Where() is not solution for me as I need to write more detailed filter that is impossible to write using Where.

## Goals
To have ability to use variables substitution into predicate.
Sample:
.Filter("DoneTime BETWEEN {%@, %@}", date1, date2);

This is pseudocode -- I'm not sure that its written with correct syntax:

.Filter("MaxRepeatsPerMonth == 0 OR (HistoryItems.DoneTime BETWEEN {%@, %@}).@count <= MaxRepeatsPerMonth", date1, date2); 

## Expected Results
.Net realm have ability to substitute values into Filter's predicate

## Actual Results
No ability to substitute dates into predicate. 

In my case -- in predicate with BETWEEN keyword.

And writing dates manually will return invalid predicate exception because of incorrect DateTime format. Predicates' dateTime must be sth like "566752095.510604". So it's impossible even to pass it manually using DateTime.ToString() method.

## Version of Realm and Tooling

Realm Ver: 3.3.0

**Comment by nirinchev** [comment]
The string format of dates accepted by Realm is `yyyy-MM-dd@HH:mm:ss`.

**Comment by ukushu** [comment]
@nirinchev  I have used `yyyy-MM-dd@HH:mm:ss` here:

`.Filter("HistoryItems.DoneTime BETWEEN {" + monthStartStr + ", "+ monthEndStr + "}");`

and it's still returns the same error:

> Realms.Exceptions.RealmException: 'HistoryItems.DoneTime BETWEEN {2018-11-30@23:59:59, 2019-01-01@00:00:00}:1:22(22): Invalid predicate.'

Just for being sure that HistoryItems.DoneTime is accessible you can chec this code:

```
public class Quest : RealmObject
{
    [PrimaryKey]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    public DateTimeOffset StartDate { get; set; }
    public DateTimeOffset EndDate { get; set; }

    public string Name { get; set; }

    public int MaxRepeats { get; set; } 

    [Backlink(nameof(HistoryItem.Quest))]
    public IQueryable<HistoryItem> HistoryItems{ get; }       
}

public class HistoryItem : RealmObject
{
    [PrimaryKey]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    public DateTimeOffset DoneTime { get; set; }

    public Quest Quest { get; set; }
}
```
And by the way:  even if this will work -- still this is a lame hack, but not native support of substitution values in correct format/way like it's realized in another languages.

**Comment by nirinchev** [comment]
I agree, ideally we'd like to provide better support for the `Filter` functionality with value substitution like in realm-js, but that hasn't been a high priority task. In any case, I'd like to offer a few pointers so you don't have to wait until the feature is implemented:

1. The .NET predicate support is based on/inspired by NSPredicate, but is not equivalent to it. An up-to-date resource for the supported operators can be found [here](https://realm.io/docs/javascript/latest/api/tutorial-query-language.html).
2. The exception that is thrown indicates the location of the invalid predicate - in this case, it's line 1, column 22, which is the `BETWEEN` statement. That is because `BETWEEN` is not supported by the Realm query parser (it may be supported by the Cocoa SDK, but that is because it uses the native NSPredicate parser).

Luckily `BETWEEN` is fairly easy to emulate using the comparison operators, so your query could be something like:

```csharp
.Filter($"HistoryItems.DoneTime >= {monthStartStr} && HistoryItems.DoneTime <= {monthEndStr}");
```

**Comment by nirinchev** [comment]
Filed an issue with Core to track improvements in the error messages: https://github.com/realm/realm-core/issues/3198

**Comment by nirinchev** [comment]
I'll keep this open until we provide support for value substitution because I think it makes sense, regardless of the fact that there's a workaround.

**Comment by nirinchev** [comment]
On a second thought, I filed a new issue to track that as it felt cleaner to separate the two: https://github.com/realm/realm-dotnet/issues/1822
