### ISSUE TITLE
RealmWeaver: Update needed to support future fody versions

### ISSUE THREAD

**Issue by tom-englert** [realm/realm-dotnet#1820]
As of Fody 3.2.5 the strategy to lookup weavers has changed:
https://github.com/Fody/Fody/wiki/AddinSearchPaths

The legacy lookup will be no longer supported in the next versions of Fody, so this weaver needs to add the props file to the NuGet package to be usable with future Fody versions.

**Comment by jsmarcus** [comment]
Fody 4.0.x is out so this is now a gating issue for updating.

**Comment by karlingen** [comment]
+1

**Comment by LumiumEngine** [comment]
This is still an issue as of Fody 4.0.2

**Comment by jsmarcus** [comment]
Fody is now at 4.2.1. Will one of the maintainers comment on the status of this issue?

**Comment by nirinchev** [comment]
The status is visible within github - the issue is open and we haven't resolved it yet. We plan to resolve it, but don't have a public timeline yet. The workaround is to use a 3.x version of Fody.

**Comment by nirinchev** [comment]
This has been fixed and will ship with Realm 4.0.

**Comment by cemheren** [comment]
What is the supported Fody version for Realm 3.2.0 ?

**Comment by nirinchev** [comment]
The supported Fody version for each Realm version is listed in the dependencies section of the nuget package.

**Comment by pikausp** [comment]
Is upgrading Fody to the latest 5.x something you would consider right now?

**Comment by nirinchev** [comment]
When Realm .NET 4.0 ships, it will be compatible the latest version of Fody at the time. We don't typically provide specific delivery dates, but we have high degree of confidence that it will ship before the end of the month.

**Comment by VaslD** [comment]
Please keep this issue open until the bugfixed version of Realm ships. After all that's how issues work, they should only be closed when a **release** fixes them. *Closed - We already knew* or *Closed - will fix next month* are bad practice, and causes duplicated issues.

Also consider adding a version constraint on Fody dependency in NuGet spec because it seems each major upgrade of Fody affects Realm somewhat. Better note it down somewhere that "Fody upgrades may break Realm." Fody is a popular foundation that many tools depend on, it gets silently upgraded quite often if users were not paying attention.

**Comment by DeadPenguin** [comment]
Realm and Fody are both now on the newest version (4.0.0 and 5.0.6) but I'm getting 
`Fody: No weavers found for the configuration entries RealmWeaver. Add the desired weavers via their nuget package`
everytime I'm trying to build, without changing anything in the code, dependencies or otherwise. Do I have to downgrade Realm or Fody for the time being, or is this also related to the aforementioned compatibility-issues?

**Comment by nirinchev** [comment]
The RealmWeaver was renamed to just Realm. I'll update the docs to note that but you can just go and change it manually in the FodyWeavers.xml file.

**Comment by mahoekst** [comment]
I still get this error. My FodyWeavers.xml file in my .NET Console test project is:

<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <Realm/>
</Weavers>

**Comment by kwbskf** [comment]
Today I upgraded Realm .NET in a solution to 4.1.0, and suddenly I get the "No weavers found for the configuration entries RealmWeaver" error, but changing FodyWeavers.xml's element from RealmWeaver to Realm did not help (same error).  I then tried upgrading Fody (to 5.1.1), but that also made no difference.  The dependency section on the Realm 4.1.0 NuGet package says it needs Fody (>= 4.0.2), so this should work.  I even tried downgrading Fody to 4.0.2, to no avail.  The above says that this problem was fixed in Realm 4, doesn't it?  And this issue is closed.  But obviously it is still happening.  What is the correct solution to this problem?

**Comment by kwbskf** [comment]
I wrote:

> changing FodyWeavers.xml's element from RealmWeaver to Realm did not help (same error). 

Well, duh, that should have been my clue -- the error message still said "RealmWeaver".  It's because I only edited the FodyWeavers.xml in one of the two projects, but not the other.  Once I edited them both, all was well.  Sorry about that.  I even re-upgraded Fody and it still worked.  :-)

**Comment by jaykannan** [comment]
Any update on this issue?

**Comment by nirinchev** [comment]
The issue is closed, which means it has been resolved. If you have a problem using Realm with a particular Fody version, please open a new issue.
