### ISSUE TITLE
Realm Cloud allows additive change when property changed from unmapped to mapped

### ISSUE THREAD

**Issue by VagueGit** [realm/realm-dotnet#1950]
Change this property
`public string ItemCode { get; set; }`
to this
```
[Required]
[MapTo(nameof(ItemCode))]
private string _ItemCode { get; set; }
public string ItemCode
{
    get => _ItemCode;
    set => _ItemCode = value;
}
```
Realm does not detect Required is an additive change, which is not allowed with Realm Cloud.

**Comment by nirinchev** [comment]
Sorry for the super late response - I'm revisiting old issues. To get to the bottom of this, I'll need more context, but the Realm SDK doesn't inherently detect detructive changes. It's the server that does so and rejects them. If you haven't opened the Realm on this device previously or you wiped your local storage, the server error can be caught by subscribing to `Session.Error` or by opening the Realm asynchronously. I spent some time verifying it works and I couldn't reproduce any surprising behavior.

Due to the age of the issue and due to my inability to repro anything concerning, I'll be closing it, but feel free to reopen if it's still a problem for you.
