### ISSUE TITLE
GetInstanceAsync does not throw exception if Realm doesn't exist

### ISSUE THREAD

**Issue by olegfresh** [realm/realm-dotnet#2003]
try
{
    realm = await Realm.GetInstanceAsync(config); // Will throw if server Realm doesn't exist
}
catch
{
    realm = Realm.GetInstance();
}

**Comment by olegfresh** [comment]
I am using NuGet v4.3

**Comment by nirinchev** [comment]
This is by design - did you expect it to throw?

**Comment by olegfresh** [comment]
@nirinchev  yet. We are blocking user interaction while loading Realms. Users can enter invalid Realm names.

**Comment by nirinchev** [comment]
This is not possible via `GetInstanceAsync` - it is designed to create a Realm if it doesn't exist, similar to `GetInstance`. In fact, there's no way from the SDK to tell if the server Realm exists or not. What's the use case - who creates the Realms on the server and why are users allowed to input arbitrary names?

**Comment by olegfresh** [comment]
<img width="948" alt="Screen Shot 2020-08-25 at 12 29 52 PM" src="https://user-images.githubusercontent.com/16905530/91201849-f79af300-e6ce-11ea-93a7-b0cd6db24c54.png">

**Comment by olegfresh** [comment]
@nirinchev  my understanding is that it was possible in 2017? See screenshot above.

**Comment by nirinchev** [comment]
Yes, this was a bug that we've since resolved. The desired behavior is for `GetInstanceAsync` to create a Realm if it doesn't exist and this has been the case for a while now.

**Comment by olegfresh** [comment]
@nirinchev is it possible to throw exception in this case? This would help us to properly handle this use case.

**Comment by nirinchev** [comment]
No, this behavior is controlled by the server - the SDK just ensures that data is downloaded before completing the task. You can probably use the permissions API to get a list of the Realms the user has access to: [`user.GetGrantedPermissionsAsync(Recipient.CurrentUser))`](https://realm.io/docs/dotnet/4.2.0/api/reference/Realms.Sync.User.html#Realms_Sync_User_GetGrantedPermissionsAsync_Realms_Sync_Recipient_). Then instead of allowing users to input arbitrary names, they should choose one of the available ones.
