### ISSUE TITLE
How to get IAsyncEnumerable<T> from query?

### ISSUE THREAD

**Issue by MhAllan** [realm/realm-dotnet#2006]
I am wondering if IAsyncEnumerable<T> is supported in the Realm queries? and if so, how to get it, and if not how to do a workaround?

**Comment by nirinchev** [comment]
It's not supported. Why do you need IAsyncEnumerable? Does the synchronous version not work for your use case?

**Comment by MhAllan** [comment]
Hi @nirinchev , It works pretty well, But the interface is designed regardless to the implementation and that's how it should be. So interface methods are written with IAsyncEnumerable<T> return type but Realm isn't able to implement such a methods

**Comment by nirinchev** [comment]
Not sure what you mean there. There are many interfaces out there and Realm collections can't possibly implement all of them. We don't implement `IAsyncEnumerable` because we haven't seen a reason to. The fact that the interface exists is not compelling enough of a reason.

**Comment by MhAllan** [comment]
Sorry but the fact is that: All interfaces should exist first and their signature shouldn't be determined by anything but how they should be. An IO method should be async and IO that returns multiple item should have the choice to do that asynchronously than buffering and looping more than once.

**Comment by nirinchev** [comment]
As mentioned, while the `IAsyncEnumerable` interface exists, it doesn't mean every collection should implement it. Realm collections do not implement it because we don't see the value in doing so. The way Realm is designed, it would be fairly useless to asynchronously iterate over a collection, because Realm does not pull data from the database upon iteration. Instead, it gives you a pointer to an object and its properties are read from the database only upon accessing them. Since property access is synchronous and is generally more expensive than iterating over a collection, it makes little sense to implement `IAsyncEnumerable`.

If you need to pass a Realm-originating collection to a method that expects an `IAsyncEnumerable<T>`, you need to wrap the Realm collection and provide the implementation yourself.

I'm closing this issue because we have no immediate plans to implement `IAsyncEnumerable`.
