### ISSUE TITLE
v5.0.1 upgrade crashes with "invalid mnemonic"

### ISSUE THREAD

**Issue by Dids** [realm/realm-dotnet#2023]
## Goals

Trying to upgrade to Realm .NET 5.0.1.

## Expected Results

Expected the new version to upgrade any existing Realms, as usual.  
Note that everything works fine if dealing with a fresh installation/new local Realm(s).

## Actual Results

```
Unable to open a realm at path '/Users/user/Library/Developer/CoreSimulator/Devices/1062746D-C016-4AE6-99D4-C00E8C48DE4C/data/Containers/Data/Application/8694ABB4-8F65-4FE0-ABEE-3137E7C3F3FB/Documents/realm-object-server/io.realm.object-server-utility/metadata/sync_metadata.realm': Invalid mnemonic. top_ref[0]: 
```

## Steps to Reproduce

Use Realm .NET 4.3.0 + Realm Cloud, then upgrade to 5.0.1 and run it again.

This can also be reproduced by simply downgrading back to 4.3.0, running a fresh application once, upgrading back to 5.0.1 and running the application again.

## Version of Realm and Tooling

- Realm Object Server Version: v3.28.2 (Realm Cloud)
- Flavor:
  - [x] Realm Cloud
  - [ ] Self-Hosted
- Client SDK Version: 5.0.1
- Client OS & Version: macOS 10.15.6 (iOS 13 target, running in simulator)

More information:
![Näyttökuva 2020-9-10 kello 10 56 39](https://user-images.githubusercontent.com/3455449/92697835-670e1500-f354-11ea-9086-d56b194b9126.png)

**Comment by nirinchev** [comment]
Hm... I wonder if that has to do with the encryption misconfiguration that 4.3.0 introduced. Can you try opening the sync_metadata.realm in Studio - I believe it will detect if a file is encrypted instead of crashing. You can also send me the file at nikola.irinchev@mongodb.com and we'll take a look.

**Comment by Dids** [comment]
You're very likely on to something:
![Näyttökuva 2020-9-10 kello 12 11 36](https://user-images.githubusercontent.com/3455449/92708459-cf61f400-f35e-11ea-974b-3cca7909e2e5.png)

I'll email the file in just a minute, thanks!

**Comment by nirinchev** [comment]
Yeah, so this looks like an encryption problem. I'll confirm with the team, but I believe it will only affect simulators upgrading from 4.3.0 to 5.0.1 - I don't think it'll affect actual devices. After making a backup of the file, you can try calling `SyncConfiguration.Initialize(UserPersistenceMode.NotEncrypted, resetOnError: true)`. I expect that this will catch the error and reset the metadata file. Note that this will remove all currently logged in users for this device.

**Comment by Dids** [comment]
Alright, I'll give that a shot and will also test on a device in a bit.

Also forgot to note that I am indeed using encryption: `SyncConfigurationBase.Initialize(UserPersistenceMode.Encrypted, CreateEncryptionKey(...));`

**Comment by Dids** [comment]
Calling `SyncConfigurationBase.Initialize(UserPersistenceMode.NotEncrypted, resetOnError: true);` instead of `SyncConfigurationBase.Initialize(UserPersistenceMode.Encrypted, CreateEncryptionKey(...));` (or both in order) didn't fix it, same exception gets thrown.
Testing device builds next.

**Comment by nirinchev** [comment]
Oh, you're setting up encryption yourself. That messes up my theory 😅 Does this happen on a new project after upgrading from 4.3.0 to 5.0.1 or is it only with your existing one? If we have a repro case where running an app with 4.3.0, then upgrading results in this crash, it would be super helpful in tracking down the root cause.

**Comment by Dids** [comment]
Sure, give me about an hour and I should have a minimal repro!

**Comment by Dids** [comment]
Sorry for the delay, but so far I haven't had much luck reproducing this in a brand new project. Even copied the encryption key logic, yet it still doesn't crash.

I'll keep adding in more app specific features and hopefully it will crash, eventually. Otherwise I'm not entirely sure what the issue is.

**Comment by Dids** [comment]
Still unable to replicate, but what I _can_ tell is that the crash happens very early on, so before any encryption is setup or any Realm is even opened.

**Comment by Dids** [comment]
This shows (and confirms) that it actually crashes on the first call to `Realms.Sync.*` call, and whether or not I call `SyncConfigurationBase.Initialize(...)` before or after doesn't seem to matter. In fact, if I do call `SyncConfigurationBase.Initialize(...)` before anything else, then it crashes on that instead of the next sync related call.

![Näyttökuva 2020-9-11 kello 13 47 06](https://user-images.githubusercontent.com/3455449/92916442-2c7ca900-f436-11ea-840e-b36de209d1ad.png)

**Comment by Dids** [comment]
@nirinchev Even though I didn't manage a repro, I did manage to fix this for this specific application.

I was essentially trying to access `Realms.Sync.User.AllLoggedIn` _before_ calling `SyncConfigurationBase.Initialize()`, which was causing the crashes.

The encryption key for the `SyncConfiguration` is user specific in this application, is that wrong?  
Additionally, the encryption key used in `QueryBasedSyncConfiguration` is application specific, so I would like to know if both of these are the correct way to go about this, or if I've managed to flip the logic around?

In any case, I removed any `Realms.Sync` calls before the `SyncConfiguration` initialization, as well as setting `resetOnError: true`, just in case.

**Comment by nirinchev** [comment]
Yeah, calling `AllLoggedIn` before `Initialize` would totally explain this, `AllLoggedIn` will internally call initialize with the default values (unencrypted on simulator/encrypted on device) and then you would override that by telling it to encrypt everywhere.

The encryption key for the metadata Realm (the one that stores all users and their access tokens) should not be user-specific - it can be device specific or application specific, but on the same device, you should always call `SyncConfigurationBase.Initialize` with the same encryption key. For iOS devices, we have native access to the keychain API, so we just generate a random key and store it there. On Android, the keystore API are introduced in a version higher than the minimum supported version by Realm, so we don't use it. If you're only targeting recent Android versions, you should just do the same - check for the key presence in the keystore and if it's there use it, otherwise generate a new one and store it for later.  

The encryption keys for each Realm containing user-data (e.g. opened via `Realm.GetInstance`) can be user-specific, or even path-specific (i.e. you can open `/~/cars` and `/~/contacts` with different encryption keys). Obviously, these encryption keys should be stable across application launches, otherwise you won't be able to read the data that's already in there.

**Comment by Dids** [comment]
Thanks, that definitely explains it!

Any idea why the Realm .NET library updates have worked fine until now though? I'm assuming something changed that's now triggering this, as this particular code/user checks hasn't been changed in ages.

**Comment by Dids** [comment]
Closing this in any case, thank you! 😄
