### ISSUE TITLE
Fody doesn't load Realm models in referenced project

### ISSUE THREAD

**Issue by SeriousM** [realm/realm-dotnet#2029]
## Goals

I try to read realm files from different sources and therefore I separated the model definitions in different projects to avoid collisions.

Example: I have a realm file with the type `Cat` with property "description" in project A and `Cat` in project B with property "desc".
Both `Cat` classes are inherit from RealmObject.
There is a also the console app that references project A and B and invokes a reader class, depending which `Cat` I need to read.

I Added `Realm` nuget package to all three projects and the FodyWeavers.xml files contains all the `<Realm />` entry.

I guess Fody doesn't kick in and none of the classes are found.

This is my code to read the realm files:

```cs
  var realmConfig = new RealmConfiguration(RealmDbInfo.LastRealmDb.FullName);
  // realmConfig.ObjectClasses = new[] { typeof(Cat) };
  using (var realmdb = Realm.GetInstance(realmConfig)) { /* do stuff */ }
```

Adding the ObjectClasses directly throws the error that `Cat` doesn't contain any properties, avoiding it throws the error that no RealmObject was found.
I also tried to add `[Preserve(AllMembers = true)]` to the `Cat` classes but that didn't worked.

Reading the realm files as dynamic works but is far away from optimal.

I read all day long in stack overflow, the fody configuration, tried fody addins to load assemblies and now I need to ask you if you could help me with this issue.

Please, tell me how I can configure a multi-project solution with realm models in referenced projects.

## Version of Realm and Tooling

- Client SDK Version: Realm 5.0.1, Fody 6.2.5
- Client OS & Version: Windows 10

**Comment by nirinchev** [comment]
Can you upload a simple project that reproduces the issue? Our tests are structured in a similar way and they do work fine, so I'm guessing it's some corner case that's poorly handled.

**Comment by SeriousM** [comment]
Thank you very much for your help! I also looked at the tests but didn't found anything special which enables this scenario.
I've just sent you an email to help@realm.io with the minimal project including a stripped version of the realm database.

Please have a look at the IosRealmDbReader:
```cs
// #1 - Exception: Scan doesn't have any properties
realmConfig.ObjectClasses = new[] { typeof(Scan) };
realmConfig.IsDynamic = false; // default

// #2 - Exception: No RealmObject found
realmConfig.ObjectClasses = null; // default
realmConfig.IsDynamic = false; // default

// #3 - works, but is very hard to read the data
realmConfig.ObjectClasses = null; // default
realmConfig.IsDynamic = true;
```
I hope you can help me, thanks!

**Comment by SeriousM** [comment]
Another information: the classes were created with the realmdb studio -> create models.

**Comment by nirinchev** [comment]
I tried running the project and it seems like the core issue was that you didn't have the Realm nuget package added to `Adventics.RealmMigrator.Ios`. This meant that the Fody weaver wasn't processing any of the classes in that assembly.

After that was resolved, there were a few smaller issues with that project (I know it's a stripped-down version, so they may not exist in your real app, but thought it's worth pointing them out just in case):
- Using `#1` - `realmConfig.ObjectClasses = new[] { typeof(Scan) }` will fail because `Scan` references classes that haven't been added to `ObjectClasses`. If you're explicitly specifying `ObjectClasses`, you'll need to add all types that are referenced in the object graph. E.g. if you have `Plane->Engine->Manufacturer` graph, you need all three classes in `ObjectClasses`.
- RealmObjects are bound to the lifetime of the Realm, which means that if you dispose the latter, all objects that were obtained from it are going to be invalidated. So doing something like this won't work:
  ```csharp
  using (var realmdb = Realm.GetInstance(realmConfig))
  {
      scans = realmdb.All<Scan>().Where(s => s.SeeID != null).ToArray();
  }
  
  // This fails because the objects in the scans collection are no longer valid
  // scans.Select(s => s.Id).ToArray();
  ```

  Instead, you should move the `fibScans = ...` assignment within the `using` statement.

I hope this helps and if you have any further questions/concerns, don't hesitate to reach out ✌️

**Comment by SeriousM** [comment]
That worked very well, thank you! The problem was that Realm.Fody, which is the Fody addin, was referenced from the package Realm and since dotnet-core you usually don't need to extra reference referenced packages.
Now everything works and fody is working fine.

maybe you can add this information to https://realm.io/docs/dotnet/latest/#installation that the nuget packages realm AND realm.fody must be referenced whereever the classes are located.

bonus:
here I simply collect all realm object types for direct use because my `Cat` type exists multiple times:
```cs
realmConfig.ObjectClasses = GetType().Assembly.GetExportedTypes().Where(t => t.BaseType == typeof(RealmObject)).ToArray();
```

**Comment by nirinchev** [comment]
Glad to hear it works 👍
