### ISSUE TITLE
Question: ANY Working MVVM Examples for Xamarin Forms?

### ISSUE THREAD

**Issue by dgerding** [realm/realm-dotnet#2055]
Really excited about Realm but...
I've looked all over, including the 3 year old sample project in the repo here. None of examples I can find show a working MVVM stack in Xamarin Forms.  In particular, I need to see something working that doesn't get the "invoked on wrong thread" error on the _second_ or third call, or that works with more than one underlying datatype. 

Are there any xamarin forms examples out there that are current and that have more than one type? What's the real secret to get around the "wrong thread" problem on Xamarin Forms with Realm?

Thanks

**Comment by nirinchev** [comment]
Are you getting invoked on the wrong thread with the example in this repo?

**Comment by dgerding** [comment]
The sample is 3 years old and I'm on XF latest (4.8x) with a .net standard forms project. That sample doesn't build out of the box anymore - at least on my setup (VS19). I started trying to rebuild it for contemporary forms solution. My bigger worry is that all of the examples I can find for realm+xamarin are pretty old. I'll keep doing it if you think it will work. 

At some point I thought I had seen an article or post about using a single dedicated background thread to host the realm and then connecting to that instance via something like ConcurrentQueue, but I can't find that anywhere when I look.

The following method from a XF ViewModel typifies my problem. The _realm field is initialized in the constructor of the ViewModel.

In the version below the method works without complaint the first time it's called. It fails for any subsequent call with the "wrong thread" exception.


`private void AddVisitedUrl(string url)
        {
            _realm = Realm.GetInstance();
            var transaction = _realm.BeginWrite();
            var entry = _realm.Add(new VisitedUrl
            {
            
                Url = url,
                LastVisited = DateTimeOffset.UtcNow
            });

            transaction.Commit();

            
        }`

What I'm really looking for is the most reliable way to use Realm in MVVM Xamarin Forms. This is a relatively large mobile app project with probably something like 20 or so model types. I can't move ahead with Realm+Mongo as a sync solution until I resolve this block. (We've got an edge-first, offline capability priority)

Any suggestions really appreciated. In the meantime I'll try and get the example QuickJournal to build as XF 4.8 solution.

Thanks

**Comment by nirinchev** [comment]
I agree - we had to put the .NET SDK on the backburner for a while, so a lot of the examples/docs have code rotted. But now it's back on top of our minds and we're in the process of updating the code, docs, and examples. We expect to have a more comprehensive getting started tutorial later this year, but I'd be happy to help you with your project in the meantime.

Do you think you can share the project that is erroring out - either publicly here in the repo or just email me at nikola.irinchev@mongodb.com and I'll take a look. Also, what platform are you running this on? We had a bug on WPF and UWP where you would incorrectly get the incorrect thread error on the main thread. That got fixed on WPF in 5.1.0 and will be fixed for UWP with 5.1.2.

**Comment by dgerding** [comment]
Thanks. I've got a refactored (to latest XF/.net standards) solution running now. Should I do a pull request to replace the old one in Examples? This one runs and works. 

I don't want to change it to test my case/need (multiple viewmodels/views to push against) since it might be helpful to some as needed.

What I would add to make this a more comprehensive example, is multiple types on multiple pages, and some kind of interaction that shows I won't get the "wrong thread" error when trying to, for example, have a record change in one model/viewmodel raise or result in change/mutate behavior in another model/viewmodel.

**Comment by dgerding** [comment]
To be clear, I mean a new, running version of "QuickJournal"

**Comment by nirinchev** [comment]
Ah... I saw that a bit too late 😅 I just pushed an update to QuickJournal that updates to the latest XF. Glad to hear you got it working on your end too!

We have a bit more advanced app that uses sync (the legacy Realm Cloud one) and has a more realistic MVVM setup here: https://github.com/realm/realm-tasks/tree/master/RealmTasks%20Xamarin. Note that it will also likely require a bit of updating to get it running.

Regarding the "wrong thread" error - I will need to better understand your concerns there, but generally speaking, Realm instances are thread-bound. This means that if you want to interact with a particular instance (or its data), you need to always do it from the same thread. For applications with a UI, the general recommendation that we have is to open a Realm on the main thread and use it for any UI interaction. This means that if your viewmodel is created on the UI thread (which would typically be the case), then it's completely safe to use that Realm instance and expose data from it to the view.

If your ViewModel is created on a background thread for whatever reason, then you can't use the main thread Realm instance in the VM constructor, but you can probably use it just fine when handling events from the view as those will be dispatched on the main thread.

Finally, when you want to interact with the database from a background thread - for example, if you pull data from a server, or want to execute an expensive computation in the background and store the results to the database, you should just explicitly open the Realm when you want to use it. One thing to be aware of here is that `await`-ing tasks while the Realm is open is fine on the main thread (because the continuation is dispatched back on the main thread), but is not fine on background threads (because the continuation is dispatched on a random threadpool thread). So in the background, you can do something like:

```csharp
private async Task DoSomethingInTheBackground()
{
    var result = await PerformExpensiveComputation();
    string nextTaskData;
    using (var realm = Realm.GetInstance())
    {
        // No awaits here as we need to keep using the same thread.
        realm.Write(() =>
        {
            realm.Add(new Report { Data = result });
        });

        // Extract some data from the Realm - note that it has to be a primitive value
        // and can't be the RealmObject itself as that will get invalidated
        // when we dispose the Realm instance.
        nextTaskData = realm.Find<TaskInfo>("some-id");
    }

    // awaits are fine now because we won't be using the Realm instance.
    await DoSomethingElse(nextTaskData);

    // If you need to write to the database again, open a new instance
    using (var realm = Realm.GetInstance())
    {
        // write or read data, but again - no awaits while using the realm instance.
    }
}
```

And again - if you do get into a state where you're getting an unexpected "wrong thread" error, I'd be happy to look at the actual code and help you figure out what's causing it.

**Comment by dgerding** [comment]
Great. That's what I had done, too. I'm not allowed to send the whole project, so I'm working up a quick example solution with 2 different pages/types that mirrors that approach I'm taking with the solution that's not working. Will email link to repo shortly. Was writing this as your replied above ... so might have more. Thanks!

**Comment by dgerding** [comment]
Thanks, Nikola. I'm going to see if I can Realm Tasks solution your referenced working in a new Xamarin Forms solution, including the new navigation stack shell.

As far as my project goes, I instantiate the _realm field in the ViewModel constructor. When I call the method I referenced earlier, to add a single instance to the _realm, it works the first time. Any subsequent call raises the wrong thread problem. Same event raised and same call stack both times against, I think, the same viewmodel instance where the _realm field was instantiated. These aren't even async calls, so I can't figure out how the thread is changing in any way that would raise the error.

I'll loop back with help when I have project to reproduce my errors. thanks!


________________________________

**Comment by ianpward** [comment]
Thanks for the help here Nikola - David we are overhauling all of our .NET docs and examples and I hope to have something substantial and up to date to share with you later this month. Stay tuned
