### ISSUE TITLE
Synced Realm is empty for a short time on app startup

### ISSUE THREAD

**Issue by luccasclezar** [realm/realm-dotnet#2080]
I'm sorry for being a little too vague, but it's a weird bug and I just want to know if there's a known cause.

So, most of the time Realm behaves normally, but randomly one of the Realms in my app (I use 5 Realms and none of the others have this issue) starts having a delay to get any item from it. I'm sure the Realm is already synced, so it should work, but if I try this code:

```C
var realm = Realm.GetInstance(fullSyncRealmConfig);
realm.All<SomeClass>().First();
```

an exception is thrown at line 2 (Sequence contains no matching elements).

The code works if I simply add a delay of 250ms before running it, which would make sense if the Realm wasn't synchronized, but it should be, as when this issue starts happening it doesn't stop until I erase the app data and re-sync it (meaning it has plenty of time to re-sync between sessions and stop bugging, but it doesn't until I manually sync).

I really tried to understand what is happening, but I don't have a clue. So, like I said, I know this is a vague description, but does someone know what could be causing this issue? Like not disposing of opened Realms, closing the app mid-sync, etc.?

The steps of the problem would be something like:

1. Start app.
1. Run `Realm.GetInstanceAsync(fullSyncRealmConfig)` and wait synchronization.
1. Close app.
1. Start app again (already synced).
1. Try to run `Realm.GetInstance(fullSyncRealmConfig).All<SomeClass>().First()`.
1. Sequence contains no matching elements.

## Version of Realm and Tooling
* Flavor:
  * [x] Realm Cloud
  * [ ] Self-Hosted
* Client SDK Version: 5.1.2
* Client OS & Version: Android API 29

**Comment by nirinchev** [comment]
Can you upload the project that reproduces this?

**Comment by luccasclezar** [comment]
Even if I could (which I can't because it is a commercial app 😕) the issue appears randomly, sometimes it takes days to reproduce it.

As I said, I know it's very hard to help without more information, I was hoping this could have a common cause or make sense to someone who knows better how Realm works.

**Comment by nirinchev** [comment]
This is not a common issue and the only explanation I can think of is user-error related (or a bug, but without more information or a repro case, we can't really confirm this). So these are the options I can think of:

1. The query is legitimately empty. It's possible that all the objects of `SomeClass` got deleted for this particular Realm.
2. You're accidentally opening the Realm with the incorrect configuration. You haven't provided snippets from your app, but there was another user recently, who had a bug in the way the Realm configuration was instantiated, so sometimes he was passing `null` instead of a `FullSyncConfiguration` instance. That was causing Realm to open a local unsynchronized Realm, which would be empty.

These explanations don't explain why adding `await Task.Delay(250)` after opening the Realm results in the data being synchronized.

3. The initial synchronization might not have completed. E.g. if the user killed the app during the first `GetInstanceAsync`, it's possible that not all data got synchronized locally.
4. The user deleted their local data or the Realm was stored in a temporary location and the operating system deleted the local Realm database.

3. and 4. can explain the behavior you're describing, but are also less common.

Unfortunately, without more information, I don't think we have a way to diagnose this further. My recommendation would be to take a look again at the logic around opening the Realm and try to find potential race conditions or corner cases. If you're unable to identify the issue and can't provide a repro case or something closer to your code, the only thing I can do is suggest a hacky workaround by handling the case of an empty query:

```csharp
public async Task<SomeClass> GetSomeClass()
{
    var result = realm.All<SomeClass>().FirstOrDefault();
    if (result == null)
    {
        await realm.GetSession().WaitForDownloadAsync();
        
        result = realm.All<SomeClass>().FirstOrDefault();
        if (result == null)
        {
            throw new Exception("Realm was synchronized but SomeClass was missing");
        }
    }

    return result;
}
```

**Comment by luccasclezar** [comment]
Thank you for your help @nirinchev!

I think I fixed this issue by explicitly calling Dispose on the Realms before changing users or when there's any kind of session/connection error. I'm not 100% sure that this will not happen anymore, but it's been a week without it so...
