### ISSUE TITLE
Compiled Bindings in Xamarin.Forms throws exception on the realm object [UWP] [IOS] [Android] 

### ISSUE THREAD

**Issue by vardansargsyan92** [realm/realm-dotnet#2270]
## Goals

I am working on Xamarin forms project targeting iOS/Droid/UWP. We are building the app in a reactive manner and use direct model bindings. So, when we bind to the model RealmObject property in an Entry for instance the value is persisted automatically. The app is working fine until I ass  [Compiled Bindings](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings) inside app xaml pages. Once I add `x:DataType` into my Xaml file the application crashes on that page.

## Expected Results

Changing the Text of the entry should persist the value of the RealmObject.

## Actual Results

On UWP/IOS/Android as soon as page is loaded I receive the following exception
`Cannot modify managed objects outside of a write transaction`.

## Steps to Reproduce

1. Open the App `TwoWayBindingSample`
2. Set UWP/IOS/ANdroid startup project 
3. Run The application

## Code Sample
here is my xaml file 

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="TwoWayBindingSample.MainPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:twoWayBindingSample="clr-namespace:TwoWayBindingSample;assembly=TwoWayBindingSample"
    x:DataType="twoWayBindingSample:MainViewModel"
    BackgroundColor="{AppThemeBinding Dark=White,
                                      Light=LightGray}">



    <StackLayout
        Padding="20,30"
        HorizontalOptions="FillAndExpand"
        VerticalOptions="Center"
        Spacing="20">

        <Label
            Text="{Binding Title}"
            FontSize="Large"
            FontAttributes="Bold"
            TextColor="{AppThemeBinding Light=Gray,
                                        Dark=LightGray}"
            HorizontalTextAlignment="Center" />

        <Label
            Text="{Binding CurrentProduct.Name}"
            FontSize="Medium"
            TextColor="{AppThemeBinding Light=Black,
                                        Dark=DarkBlue}"
            HorizontalTextAlignment="Center" />
        <Entry
            Text="{Binding CurrentProduct.Name}"
            HeightRequest="50"
            TextColor="{AppThemeBinding Light=Black,
                                        Dark=DarkBlue}"
            BackgroundColor="{AppThemeBinding Dark=White,
                                              Light=LightGray}"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="Center" />
    </StackLayout>

</ContentPage>
```

When I don't use `x:DataType="twoWayBindingSample:MainViewModel"` then the app works fine. However after adding this and using direct binding `<Entry Text="{Binding CurrentProduct.Name}"/>` I am getting a Realm exception telling me `Cannot modify managed objects outside of a write transaction`.

## Version of Realm and Tooling

- Realm 10.1.1
- Xamarin Forms 5.0.0.2012
- Microsoft Visual Studio Community 2019 Version 16.8.6

## Sample
[TwoWayBindingSample.zip](https://github.com/realm/realm-dotnet/files/6049955/TwoWayBindingSample.zip)

**Comment by nirinchev** [comment]
We don't support implicit transactions for compiled bindings. We're exploring ways to enable that but the only workaround for now is to either disable compiled bindings or open a transaction manually.

**Comment by vardansargsyan92** [comment]
HI @nirinchev . Thanks for response. So I should avoid direct bindings and open a transaction manually. Right?

**Comment by vardansargsyan92** [comment]
It’s a pity I can not use the compile bindings with the realm.

**Comment by nirinchev** [comment]
You can also add some boilerplate to your models that will enable using compiled bindings. Here's an example of what you can do:

```csharp
public class Person : RealmObject
{
    public string Name { get; set; }

    public string NameBinding
    {
        get => IsValid ? Name : null;
        set
        {
            if (!IsManaged || Realm.IsInTransaction)
            {
                Name = value;
            }
            else
            {
                Realm.Write(() => Name = value);
            }
        }
    }

    protected override void OnPropertyChanged(string propertyName)
    {
        base.OnPropertyChanged(propertyName);

        if (!propertyName.EndsWith("Binding"))
        {
            RaisePropertyChanged($"{propertyName}Binding");
        }
    }
}
```

The basic idea is the following:
1. The `Name` property is going to be managed by Realm as usual.
2. The `NameBinding` property gets and sets `Name`, but has some extra logic:
  * In the getter, if the object is not valid, it returns the default value for the type - e.g. `null` for string or `0` for int, etc. This is needed in case the object gets deleted - you don't want your bindings to start throwing exceptions.
  * In the setter, if the object is unmanaged (i.e. not added to the Realm yet) or if the Realm instance is already in a transaction, it just calls the `Name` setter. Otherwise, it creates a transaction, sets `Name` and then commits the transaction.
3. You're overriding `OnPropertyChanged` and raising `PropertyChanged` for the corresponding `xxxBinding` property for each `xxx` property.

It's a bit of a hassle, but with that approach you can then use the `xxxBinding` properties to pass to a two-way databinding. You can also abstract a lot of that code away, so you don't have to repeat it for every property.

As mentioned, we would very much like to support compiled bindings at some point, it's just that there's no obvious solution there.

**Comment by vardansargsyan92** [comment]
@nirinchev  Thank you a lot for your efforts. I'll try this and  I think this workaround would be helpful for a lot of people )). Happy to see that you are working on supporting compile bindings. Thank you
