### ISSUE TITLE
"Bad changeset (DOWNLOAD)"

### ISSUE THREAD

**Issue by R-Ziegler** [realm/realm-dotnet#2463]
.Net Framework 4.7.2 in VS 2019. Realm 10.2.0 nuget package. The following code causes the error.

`Realms.Sync.App app = Realms.Sync.App.Create(RealmConnectionInfo.AppID);`
`Realms.Sync.Credentials creds = Credentials.EmailPassword(RealmConnectionInfo.Username, RealmConnectionInfo.Password);`
`Realms.Sync.User user = await app.LogInAsync(creds);`
`SyncConfiguration config = new SyncConfiguration(RealmConnectionInfo.Partition, user);`
`var realm = await Realm.GetInstanceAsync(config);`

Error message: {"A system error occurred while opening a Realm. See InnerException for more details."}
Inner Exception: {"Bad changeset (DOWNLOAD)"} Error Code: 112

**Comment by nirinchev** [comment]
Moved this to `realm-dotnet` as this is the repo that hosts the .NET SDK. Unfortunately, the information here is not enough to diagnose the issue - to understand what is happening, we'll need trace logs and information about your app. Since the trace logs may contain sensitive information, can you please open a ticket on https://support.mongodb.com/ and a support engineer will work with you to collect the necessary information.
