### ISSUE TITLE
[Bug]: Task.WaitAll Upload or Download freeze

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2567]
### What happened?

When use Task.WaitAll(RealmInstance.GetSession().WaitForDownloadAsync(),RealmInstance.GetSession().WaitForUploadAsync());

They freeze and never return.

I'm not sure if it's a bug or bad use.

### Repro steps

Call Task.WaitAll(RealmInstance.GetSession().WaitForDownloadAsync(),RealmInstance.GetSession().WaitForUploadAsync());
not work, freeze , only calling one after other works.

await RealmInstance.GetSession().WaitForDownloadAsync();
await RealmInstance.GetSession().WaitForUploadAsync();

### Version

10.3.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Client OS and version

Windows 10

**Comment by nirinchev** [comment]
This sounds like a deadlock caused by blocking while waiting for an asynchronous operation to complete. By blocking the main thread waiting for the `WaitForDownloadAsync()`, you're creating a deadlock, because the continuation of `WaitForDownloadAsync` needs to be dispatched back on the main thread, which is now blocked. Instead of using `WaitAll`, you can use `WhenAll` and await the resulting task:

```csharp
await Task.WhenAll(
    RealmInstance.GetSession().WaitForDownloadAsync(),
	RealmInstance.GetSession().WaitForUploadAsync()
);
```

**Comment by carbonete** [comment]
Thanks for help.
