### ISSUE TITLE
Update documentation for building the wrappers

### ISSUE THREAD

**Issue by daawaan** [realm/realm-dotnet#2748]
### Description

I am currently trying to make a pull request but the documentation for building the wrappers seem to be outdated

Edit: I am using Rider by the way, is Visual Studio really needed for rebuilding it? I'm also fine with just a quick short information to start me up in making a pull request in the meantime

**Comment by papafe** [comment]
Hi @daawaan is there anything specific in the documentation that is not updated? Did you try to do something and you did not succeed?

I think Rider should be fine too. We use Visual Studio internally though, so I can't guarantee you won't have any problem

**Comment by daawaan** [comment]
Hello there. As a backup for some cases, I have Visual Studio installed so it shouldn't be a worry. I actually can't follow what I'm supposed to do to download/build the realm wrapper dlls. So far basing on the [wrappers/readme.md](https://github.com/realm/realm-dotnet/blob/master/wrappers/README.md), I was only able to run `git submodule update --init --recursive` in the source directory, but I am not sure if that is supposed to download the missing dlls since it currently isn't adding anything in the source. Am I supposed to build all the dlls from their c++ sources or is there an alternative way to just download prebuilt binaries? since I'm not planning to change the wrappers source code anyway

![Screenshot (116)](https://user-images.githubusercontent.com/53972232/145787526-604d65dd-5b10-4abc-9176-cb30fa499cbe.png)

**Comment by papafe** [comment]
So, you're right, that link should point to the `wrappers` folder, not `wrappers/src`. The link that it was talking about is the one that you see in the picture, at the top (`realm-code @ 802...`). 
![FB95F1BA-9BFD-463D-93C9-50DE5015C6D0](https://user-images.githubusercontent.com/4850119/145796785-86d03f84-e83d-4180-a7c1-1d41c9235119.png)
To give some context, the `realm-dotnet`project is structured in a way that it uses the `realm-core` project as a submodule, in particular for the wrappers. This means that you need to have the `realm-core` project at a certain commit to be able to build the wrappers (the commit is that `@802...` that you see in the link).
When you run that command it should initialize the submodule and retrieve all the code. Now if you go into the `wrappers` folder, you should have the `realm-core` folder populated. 
And yes, you would need to build the wrappers yourself in order to run the code.

**Comment by daawaan** [comment]
Hmm is it fine if I can just extract the prebuilt native binaries from the nuget package and add them to their designated locations based on the csproj?

**Comment by daawaan** [comment]
Hello, I was able to successfully run the tests without building any of the native binaries by using the prebuilt ones from the nuget packages. Unfortunately, it only works in a Release configuration. Is it possible to include downloadable prebuilt binaries for both Release and Debug configurations in the (wrappers/readme.md)[https://github.com/realm/realm-dotnet/blob/master/wrappers/README.md]?

**Comment by papafe** [comment]
This is something that we do not do right now, but we could think about it in the context of our CI. 
Did you have any issues trying to build the wrappers for Windows?

**Comment by papafe** [comment]
I agree that the instructions for linux, macOS, ios and Android are more difficult to follow. That is also why most of the times we suggest to build the Windows one and let the CI discover eventual issues with the other platforms (if necessary)
