### ISSUE TITLE
[Bug]: Upgrade to 10.8.0 lost logged users

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2774]
### What happened?

When upgrade from 10.6.0  to 10.8.0 , logged user in sync Realm disappear.

When open Realm no exception is generated.

I try downgrade to 10.6.0 but in this case i receive a exception " Provided schema version 5 is less than last set version 6. "

### Repro steps

update nugget 

### Version

10.8.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Client OS and version

Windows 10

**Comment by nirinchev** [comment]
Does this happen on UWP or regular windows desktop app?

**Comment by carbonete** [comment]
UWP xamarin forms 5

**Comment by carbonete** [comment]
This Sync repository is Encrypted.

**Comment by fealebenpae** [comment]
Hi @carbonete,

In UWP apps we persist logged-in users across app runs in a local realm file you can find in your app's [LocalFolder](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.localfolder?view=winrt-22000#windows-storage-applicationdata-localfolder) under `mongodb-realm/{your_realm_app_id}/metadata/sync_metadata.realm`.

We recently fixed a bug where a user's synchronized realm files might not be deleted when the user is removed from the application and that required an update to the metadata realm (hence not being able to downgrade without deleting it manually). The metadata realm should be preserved across upgrades, though, and we haven't heard other reports of logged-in users disappearing from the app, so I'm not sure if the bug fix I mentioned can have caused this.

Is it possible that you have changed the UWP app's identity, or otherwise have caused its LocalFolder to be wiped or recreated when deploying the new version of the app? In any case, the app should continue the function normally even if the metadata is reset - users would just need to log in again.

**Comment by fealebenpae** [comment]
If you can recreate this error in a new blank app I'll be happy to debug it, otherwise there is little I can do without a way to reproduce the bug.

**Comment by carbonete** [comment]
@fealebenpae thanks 

After user  made login again, app works fine.

I don't know if it's relevant in this case, but i'm using GetSsession(), and now i use SyncSession properproperty.

I'm closing this.
