### ISSUE TITLE
[Bug]: Realm fails on Hololens UWP application with "Unable to load DLL 'realm-wrappers'"

### ISSUE THREAD

**Issue by TigerLouck** [realm/realm-dotnet#2817]
### What happened?

# Goals
I am attempting to use a Realm in a Hololens application
# Expected Results
The Realm works in-editor and on device
# Actual Results
it fails on device with a DLLNotFoundExeption for realm-wrappers.dll, 

### Repro steps

Add Realm and the Mixed Reality Tool Kit to a Unity project, and configure for deployment to a Hololens. In a script attempt to get a Realm instance. Observe that the realm is accessible in-editor. Using the MRTK build window, build the unity project and then the .appx, and deploy it to a Hololens. In the logs you should see a `DLLNotFoundExeption` for `realm-wrappers`. I've uploaded a project that minimally reproduces the issue here: https://drive.google.com/file/d/1GLUrmeRzhD7QuhiUmuQadj16onyAXS_X/view?usp=sharing
[UnityPlayer.log.txt](https://github.com/realm/realm-dotnet/files/8091185/UnityPlayer.log.txt)

### Version

.NET standard 2.0

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Unity

### Client OS and version

Windows Holographic

### Stacktrace of the exception/crash you're getting

```shell
: Unable to load DLL 'realm-wrappers': The specified module could not be found.
  at Realms.SynchronizationContextScheduler.Install () [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.NativeCommon.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.RealmConfiguration.CreateRealm (Realms.Schema.RealmSchema schema) [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.Realm.GetInstance (Realms.RealmConfigurationBase config) [0x00000] in <00000000000000000000000000000000>:0 
  at DemoScript.Start () [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as TypeInitializationException: The type initializer for 'Realms.SharedRealmHandle' threw an exception.
  at Realms.RealmConfiguration.CreateRealm (Realms.Schema.RealmSchema schema) [0x00000] in <00000000000000000000000000000000>:0 
  at Realms.Realm.GetInstance (Realms.RealmConfigurationBase config) [0x00000] in <00000000000000000000000000000000>:0 
  at DemoScript.Start () [0x00000] in <00000000000000000000000000000000>:0
```

**Comment by nirinchev** [comment]
Are you deploying on actual device or the emulator? And what CPU architecture are you building your project for?

**Comment by nirinchev** [comment]
Okay, then that's due to us not shipping an ARM64 slice for UWP. @fealebenpae has that in progress but we don't have a time estimate yet.

**Comment by TigerLouck** [comment]
Alright, we're sitting pretty on our end then. Is there any way for us to keep tabs on that work so we can come back to this when it's ready? Can you say what's missing? Maybe we can get something working while we wait for the official slice.

**Comment by nirinchev** [comment]
You should be able to run it on an emulator I believe. This is the original issue that's tracking this: https://github.com/realm/realm-dotnet/issues/2704.

**Comment by nirinchev** [comment]
Hey @FreakTheMighty, pretty excited to hear you folks are looking to add Realm to your Hololens project and really appreciate your offer to help. We're well underway with laying the groundwork for supporting ARM64 on Windows/UWP and hope to have something tangible that you can test with in the near future. While I can't promise concrete dates, I'm fairly optimistic about completing this in the next couple of weeks. I'll let you know if that turns out to be infeasible.

Once we have something ready, we'd really appreciate if you and your team could help by testing it out on an actual device. We've ordered some ARM64 machines to run on CI, but we don't have an estimate for when they'll arrive, so there's no way for us to verify that things actually work yet 😅

**Comment by FreakTheMighty** [comment]
@nirinchev that's great news! Yeah, let us know when you need something tested, we've got the devices.

**Comment by nirinchev** [comment]
Hey @FreakTheMighty and @TigerLouck, we have a very early build for UWP ARM64 that should hopefully run on Hololens. Since we don't have the device to test out, would you mind giving it a try. You can download the .tgz [here](https://drive.google.com/file/d/1BhNpCqq5iKhKfNsQEGCJ_vLEgT_2rfdi/view?usp=sharing) (we are going to setup nightly feed for Unity eventually, but haven't had a chance to do that yet). To install it in your project, remove the existing Realm package and choose the "Add package from tarball" option in UPM.

**Comment by TigerLouck** [comment]
The package works great, functionality is the same as in editor and nothing untoward in the logs. If anything else comes up we'll let you know, and if you need any more testing while you're waiting for your own ARM64 devices let us know.
