### ISSUE TITLE
[Bug]: Missing info in documentation of type DateTimeOffset

### ISSUE THREAD

**Issue by PawKanarek** [realm/realm-dotnet#2820]
### What happened?

Documentation states we can store DateTimeOffset type in realm, [but the TimeZone is lost when item is persisted into realm. ](https://github.com/realm/realm-dotnet/issues/1835) Please update info about losing TimeZone in your [documentation](https://docs.mongodb.com/realm/sdk/dotnet/data-types/field-types/#.net-types).
Something about conversion to UTC would be really helpful :) 
<img width="717" alt="Screenshot 2022-02-23 at 01 34 27" src="https://user-images.githubusercontent.com/15096514/155243760-2711a18b-893b-4226-a2f2-05776bff5e5b.png">

Also i didn't found info about losing TimeZone in [Troubleshooting](https://docs.mongodb.com/realm/sdk/dotnet/troubleshooting/) and I'm starting to wonder if Realm should allow [DateTimeOffset](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset?view=net-6.0), because this sounds more like storing [DateTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime?view=net-6.0).

### Repro steps

This is a documentation bug.

**Comment by nirinchev** [comment]
You're right, we should clarify that in the docs. The reason why we chose to use `DateTimeOffset` instead of `DateTime` is because the latter has some ambiguity when converting to UTC, especially when the Kind is `Unspecified`. That, combined with the fact that there's a general trend in the .NET ecosystem toward moving away from `DateTime` pushed us toward the choice of `DateTimeOffset`. If storing the timezone info is important for your app, then I'd suggest using an extra property for that - something like:

```csharp
public class MyClass : RealmObject
{
    // These are persisted in Realm
    private DateTimeOffset UtcDate { get; set; }
    private double OffsetMinutes { get; set; }

    // This is calculated
    public DateTimeOffset Date
    {
        get => UtcDate.AddMinutes(OffsetMinutes);
        set
        {
            UtcDate = value.ToUniversalTime();
            OffsetMinutes = value.Offset.TotalMinutes;
        }
    }

    // If you care about property change notifications, re-raise property changed for
    // Date if UtcDate or OffsetMinutes changes
    protected override void OnPropertyChanged(string propertyName)
    {
        base.OnPropertyChanged(propertyName);

        if (propertyName == nameof(UtcDate) || propertyName == nameof(OffsetMinutes))
        {
            RaisePropertyChanged(nameof(Date));
        }
    }
}
```

I filed a ticket for the docs team to clarify that in the documentation, so hopefully it will be less confusing going forward.

**Comment by PawKanarek** [comment]
@nirinchev thank you! That info will be very useful for anyone that works with dates and different time zones.
