### ISSUE TITLE
[Bug]:  Failed to weave assembly

### ISSUE THREAD

**Issue by Sayoj** [realm/realm-dotnet#2836]
### What happened?

A bug happened!

Everytime I want to weave the assembly it failes and I get an error. 

### Repro steps

Realm: Weave Assemblies... everytime.

### Version

10.9.0

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Unity

### Client OS and version

2020.3.26f1

### Relevant log output

```shell
[UnityEngine.Purchasing.Security] Failed to weave assembly. If the error persists, please report it to https://github.com/realm/realm-dotnet/issues: UnityEngine.UnityException: get_dataPath can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
  at (wrapper managed-to-native) UnityEngine.Application.get_dataPath()
  at RealmWeaver.WeaverAssemblyResolver.GetAbsolutePath (System.String assemblyPath) [0x0000a] in <8cbaefc5f8024ea19d500a8cb18fc0d9>:0 
  at RealmWeaver.WeaverAssemblyResolver.Resolve (System.String assemblyPath, System.Collections.Generic.IEnumerable`1[T] references) [0x00005] in <8cbaefc5f8024ea19d500a8cb18fc0d9>:0 
  at RealmWeaver.UnityWeaver.WeaveAssemblyCore (System.String assemblyPath, System.Collections.Generic.IEnumerable`1[T] references, System.String framework, System.String targetOSName) [0x00013] in <8cbaefc5f8024ea19d500a8cb18fc0d9>:0 
UnityEngine.Debug:LogError (object)
RealmWeaver.UnityWeaver/UnityLogger:Error (string,Mono.Cecil.Cil.SequencePoint)
RealmWeaver.UnityWeaver:WeaveAssemblyCore (string,System.Collections.Generic.IEnumerable`1<string>,string,string)
RealmWeaver.UnityWeaver/<>c__DisplayClass19_0:<WeaveAllAssemblies>b__0 ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()
```

**Comment by RayBrack** [comment]
I started updating my code to use Realm v10.10.0 but I now get the following error when attempting to build the solution.

The current solution uses 10.7.1 without problem.  I have tried;
•	Cleaning the solution between each build
•	Applying the updates incrementally (10.8 worked 10.9 failed)
•	Uninstalling Realm 10.7.1, cleaning the solution, then installing 10.10.0
 
Build started...
1>------ Build started: Project: CrmMongo, Configuration: Debug Any CPU ------
1>Build started 1/03/2022 2:20:27 PM.
1>Target _GetProjectReferenceTargetFrameworkProperties:
1>Target ResolveProjectReferences:
1>Target CoreCompile:
1>  Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
1>Target FodyTarget:
1>  Fody: Fody (version 6.6.0.0 @ file:///C:/Users/Raymond.Brack/.nuget/packages/fody/6.6.0/netclassictask/Fody.dll) Executing
1>    Fody/Realm: Executing weaver Realm v10.10.0+a3777199226446b969610d6c14ff04caff18d482
1>  MSBUILD : error : Fody: An unhandled exception occurred:
1>  MSBUILD : error : Exception:
1>  MSBUILD : error : Failed to execute weaver C:\Users\Raymond.Brack\.nuget\packages\realm.fody\10.10.0\build\..\weaver\netstandard2.0\Realm.Fody.dll
1>  MSBUILD : error : Type:
1>  MSBUILD : error : System.Exception
1>  MSBUILD : error : StackTrace:
1>  MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 221
1>  MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 112
1>  MSBUILD : error : Source:
1>  MSBUILD : error : FodyIsolated
1>  MSBUILD : error : TargetSite:
1>  MSBUILD : error : Void ExecuteWeavers()
1>  MSBUILD : error : Object reference not set to an instance of an object.
1>  MSBUILD : error : Type:
1>  MSBUILD : error : System.NullReferenceException
1>  MSBUILD : error : StackTrace:
1>  MSBUILD : error :    at ModuleWeaver.Execute()
1>  MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 185
1>  MSBUILD : error : Source:
1>  MSBUILD : error : Realm.Fody
1>  MSBUILD : error : TargetSite:
1>  MSBUILD : error : Void Execute()
1>  MSBUILD : error :
1>  Fody: Finished Fody 219ms.
1>Done building target "FodyTarget" in project "CrmMongo.csproj" -- FAILED.
1>
1>Done building project "CrmMongo.csproj" -- FAILED.
1>
1>Build FAILED.
1>
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Failed to execute weaver C:\Users\Raymond.Brack\.nuget\packages\realm.fody\10.10.0\build\..\weaver\netstandard2.0\Realm.Fody.dll
1>MSBUILD : error : Type:
1>MSBUILD : error : System.Exception
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 221
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 112
1>MSBUILD : error : Source:
1>MSBUILD : error : FodyIsolated
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void ExecuteWeavers()
1>MSBUILD : error : Object reference not set to an instance of an object.
1>MSBUILD : error : Type:
1>MSBUILD : error : System.NullReferenceException
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at ModuleWeaver.Execute()
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 185
1>MSBUILD : error : Source:
1>MSBUILD : error : Realm.Fody
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void Execute()

**Comment by nirinchev** [comment]
@Sayoj are you getting this error when you make changes to your code or when you click the `Weave Assemblies` button in the Tools->Realm menu? I'm trying to setup a repro project, but can't seem to trigger it. Can you try creating an empty new project and see if that too triggers the error or it's only your actual project that fails weaving?

**Comment by Sayoj** [comment]
hey @nirinchev thanks for the answer. 

I am getting this error on starting Unity and when I click on `Weave Assemblies`.

About a new project: It works on new project and it works on another project I have too. But the funny thing is that this project, where it is not working, is one which is synced in the company. So my co-worker has no problem, but I do.

I am currently developing on Windows 10.

**Comment by nirinchev** [comment]
Okay, I can see the issue and will try to workaround it shortly.

**Comment by nirinchev** [comment]
@Sayoj can you try with this build: https://drive.google.com/file/d/1FX4yagINYcYPOZEnipNKLinJB1odxjgo/view?usp=sharing? I believe it should fix your issue, but since I have no way of verifying it, I'm a little reluctant to just merge and release it.

**Comment by Sayoj** [comment]
@nirinchev yes, great! Thank you very much! It works right now
