### ISSUE TITLE
Support for Two Way bindings (.Net/C#/WPF)

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-dotnet#2902]
### Description

This may be address already but is there any way to use WPF data bindings for realm object properties ?

Currently using them results in an exception because of no write transaction.

Is there any way to overcome this so that two way bindings can be used or is there some other way to achieve this.

For this particular application it will be standalone use so micro transactions shouldn't be a problem.

**Comment by duncangroenewald** [comment]
Here is what I am currently doing

```
[Required]
        public string Name { get; set; } = "New Exposure";
        public string name
        {
            get { return Name; }
            set
            {
                this.Realm.Write(() =>
                {
                    this.Name = value;
                });
            }
        }
```

If there is an easier way to avoid duplicating every properly would love to know.

**Comment by LaPeste** [comment]
`RealmObject` already implements [INotifyPropertyChanged](https://docs.microsoft.com/dotnet/api/system.componentmodel.inotifypropertychanged). Users are not expected to write any of that.
All you need is the following:
```
[Required]
public string Name { get; set; } = "New Exposure";
```

You can find more information in our documentation at [this page](https://www.mongodb.com/docs/realm/sdk/dotnet/fundamentals/object-models-and-schemas/#data-binding-and-mvvm).

**Comment by fealebenpae** [comment]
Hey @duncangroenewald,

We provide this for Xamarin Forms two-way bindings - we hook into the data binding flow to open a write transaction for the property setter. We do this by implementing the [IReflectableType](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.ireflectabletype) interface on [RealmObjectBase](https://github.com/realm/realm-dotnet/blob/67e05668a650b2aa7e5e262fc652d9e29aac478c/Realm/Realm/DatabaseTypes/RealmObjectBase.cs#L504-L507). This basically works by returning a new `TypeInfo` object that bindings resolve against.

So right now the Xamarin Forms data binding engine sees that realm objects implement `IReflectableType` and so it calls `RealmObjectBase.GetTypeInfo()`, which returns a cached instance of the internal type [RealmObjectTypeDelegator](https://github.com/realm/realm-dotnet/blob/main/Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs). This object is what data bindings are resolved against and it overrides the `GetDeclaredProperty` method to return a special [PropertyInfo implementation](https://github.com/realm/realm-dotnet/blob/main/Realm/Realm/DataBinding/WovenPropertyInfo.cs) for woven (database-backed) properties on realm objects that knows to open a write transaction in its set method.

WPF data binding supports the exact same flow, but with [ICustomTypeProvider](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.icustomtypeprovider) instead of `IReflectableType`. We would have added support for this, but unfortunately it's not a .NET Standard 2.0 interface like `IReflectableType` is. However, you could implement `ICustomTypeProvider` on your own realm object classes yourself and use most of the code in https://github.com/realm/realm-dotnet/tree/main/Realm/Realm/DataBinding to implement the same generic solution we did.

**Comment by duncangroenewald** [comment]
Thanks for responding, I will take a look at that.
