### ISSUE TITLE
Error on Realm.GetInstance on windows

### ISSUE THREAD

**Issue by davewheatcroft3** [realm/realm-dotnet#3402]
### What happened?

When running a MAUI windows app, the first time .GetInstance is called an error happens:

LockFileEx() failed: unknown error

### Repro steps

If you simply run your sample project then this error happens.

(I had to add a Properties folder with a launchSettings.json containing:
{
  "profiles": {
    "Windows Machine": {
      "commandName": "MsixPackage",
      "nativeDebugging": false
    }
  }
}
To even get the Windows app to run.

### Version

.NET 7

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Other

### Client OS and version

Windows 10

### Stacktrace of the exception/crash you're getting

```shell
at Realms.NativeException.ThrowIfNecessary()
   at Realms.SharedRealmHandle.Open(Configuration configuration, RealmSchema schema, Byte[] encryptionKey)
   at Realms.RealmConfiguration.CreateHandle(RealmSchema schema)
   at Realms.RealmConfigurationBase.CreateRealm()
   at Realms.Realm.GetInstance(RealmConfigurationBase config)
   at QuickJournal.ViewModels.JournalEntriesViewModel..ctor() in D:\Development\realm-dotnet-main\examples\QuickJournal\ViewModels\JournalEntriesViewModel.cs:line 23
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

### Relevant log output

```shell
LockFileEx() failed: unknown error
```

**Comment by nirinchev** [comment]
@papafe can you take a look since you're updating the quickjournal anyway.

**Comment by papafe** [comment]
Sure, I'll try to reproduce it

**Comment by papafe** [comment]
I can see we need to slightly modify the project on Windows so that it can be run straight away. There is a very l[ong discussion](https://github.com/microsoft/WindowsAppSDK/issues/1762) about this, but it seems that we can also just add `<WindowsPackageType>None</WindowsPackageType>` in the project file to make the project immediately runnable. I have tried it and it works fine. I can also see that the UI isn't great, but I'll work on it.

Regarding your crash, unfortunately I was not able to reproduce it. Looking around it seems that there is a [user that got a similar exception](https://github.com/realm/realm-studio/issues/1477) when creating a realm on a WSL file system. Are you maybe trying to do something similar? 

If not, I may suggest you trying to specify the folder where the realm is placed, for example:
```csharp
var realmConfig = new RealmConfiguration(path);
var realm = Realm.GetInstance(realmConfig);
```
I suspect that there could be an issue with the filesystem where the realm is being placed, so trying with another path may help.

**Comment by davewheatcroft3** [comment]
Thanks for looking into this. I solved it with:

```
 var folder = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
  var path = Path.Combine(folder, "realm");
  return Realm.GetInstance(new RealmConfiguration(path));
```

Great time using this library so far by the way - initially just via a tests project it was all very streamlined, but then when testing on Windows I ran into this issue. Maybe could make it clearer in the documentation that for the different platforms specifying the application folder would be a good idea? Or maybe eve a CrossPlatformRealmConfiguraton which defaults the path?

**Comment by papafe** [comment]
@davewheatcroft3 Glad you like using Realm! And I'm also happy to hear it's working for you right now. 
Nevertheless I think it would be interesting for us to know why it was happening, as most of the time it's not necessary to specify the realm path. 
Do you have some "non-standard" setup on your machine maybe?

**Comment by davewheatcroft3** [comment]
So im on Windows 11 (I put 10 before - apologies!) and running the 'Windows Machine' simulator from a .net7 project. I havent altering anything that Im aware would impact the simulator but then again you know how it is over the years with development - tweak all sorts you forget about and dont put back!
As an aside - what does the default realm configuration do when deciding the file path?

**Comment by papafe** [comment]
I can imagine that over time configuration changes :)

Regarding the file path, in most cases we loop through the content of this variable and select the first folder that's writable:
https://github.com/realm/realm-dotnet/blob/01fd7b1306776591bab9e44ca24814ca027990ae/Realm/Realm/InteropConfig.cs#L38-L42

More folder could be added to this depending on the platform though
