### ISSUE TITLE
Throws leave realm open

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#503]
Run the recently-added `ConfigurationTests. ReadOnlyRealmsArentWritable` more than once and you will probably see it fail with an exception: `Realms.RealmMismatchedConfigException: Realm at path already opened with different read permissions`.

This test validates that trying to write to a readonly realm throws. It shouldn't leave the realm open, although it would be a rare case for user code to recover from this particular exception and continue.

More urgently, we should probably cope with any error by closing the realm. This may be a side-effect of the way we are throwing C# exceptions via a callback.

**Comment by kristiandupont** [comment]
This seems to happen because our `SafeHandle` derivatives increment their reference counter internally when we call Native* methods. When those trigger an exception, invoking our exception callback, they are decremented correspondingly. A temporary solution to this would be to replace our signatures with `IntPtr` and use `DangerousGetHandle()` or to reconsider our exception throwing architecture entirely.

**Comment by kristiandupont** [comment]
Fixed with #681
