### ISSUE TITLE
It's possible to reuse an TEntity as a RealmObject ?

### ISSUE THREAD

**Issue by jbravobr** [realm/realm-dotnet#543]
I'm using the Repository Pattern, since I already get the TEntity object from my ViewModel and it is inherited from RealmObject, why I can't write this directly to my realm ? I have to set all properties values from my TEntity to my realm object.

```
public bool Insert(AuthenticationToken entity)
        {
            using (var tran = _realm.BeginWrite())
            {
                try
                {
                   **that it's what I WANT to do**
                   var obj = _realm.CreateObject<AuthenticationToken>();
                   obj = entity; 

                   **OR EVEN BETTER**
                   pass the TEntity through the CreateObject ctor and it's binding it self
                   var obj = _realm.CreateObject<AuthenticationToken>(entity);
                   
                   **that it's what I HAVE to do**
                    var obj = _realm.CreateObject<AuthenticationToken>();
                    obj.AccessToken = entity.AccessToken;
                    obj.Id = entity.Id;
                    obj.RefreshToken = entity.RefreshToken;
                    
                    tran.Commit();
                    return true;
                }
                catch (RealmException rEx)
                {
                    Log(rEx);
                    return false;
                }
                catch (Exception ex)
                {
                    Log(ex);
                    return false;
                }
            }
        }
```

**Comment by kristiandupont** [comment]
Hi @jbravobr, using realm with the repository pattern is likely to cause a few annoyances like this. 

The optimal solution here would probably be if the method responsible for creating the `AuthenticationToken` could use `Realm.CreateObject` in a transaction instead of as a standalone object, so you wouldn't need the `Insert` method at all.  

If that's not possible, perhaps you could turn the `entity` parameter into a managed object? So instead of creating a new object `obj`, you call `_realm.Manage(entity)`. Note then, that subsequent changes to it will have to take place in transactions and will be persisted, also outside of `Insert()`.

We could create some way to construct a copy of an object, but we are discussing ways to get rid of `Realm.CreateObject` entirely to allow a more natural syntax, so we're hoping that we won't need it.

**Comment by jbravobr** [comment]
@kristiandupont thanks a lot for your answer ! I already going for the Managed object, so far it reduces my "problem". I really want to help Realm on Xamarin, how can I do that ?

**Comment by kristiandupont** [comment]
@jbravobr Great! The best way to help us is by keeping the feedback coming! We need to know what's important to our users more than anything. :-)

**Comment by jbravobr** [comment]
Fork the repository here, doesn't help too? It's possible to do that?
Em qua, 25 de mai de 2016 às 11:11, Kristian Dupont <
notifications@github.com> escreveu:

**Comment by kristiandupont** [comment]
Sure, you can fork it and make PR's if you feel up for it!
