### ISSUE TITLE
Migrations API

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#545]

**Comment by AndyDentFree** [comment]
See recent Slack discussions. starting [here in Bindings](https://realmio.slack.com/archives/bindings/p1466001335000015) for @AndyDentFree pushing idea of using a DSL run in ObjectStore instead of user callbacks.  

Unless they have an extraordinarily complex mapping, I think we could define a way to handle relatively simple string and numeric transforms and push that down to loop in ObjectStore for vastly higher performance.  That also makes it portable and is the foundation for OS handling computed fields and compound keys.
