### ISSUE TITLE
Fix Fody issues with Linking

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#577]
When you turn on the misnamed _linking_ (actually more like _linker stripping_ ) feature of Xamarin Studio, Fody seems to have problems. In at least one case we have found it only working for **nested** classes.

**Comment by kristiandupont** [comment]
Just to note the details, weaving itself seems to work fine, the problem is more likely with the stripping of constructors that aren't explicitly called. This is *probably* due to the requirement of the `Preserve` attribute to be in the `Android.Runtime` namespace when used on Android -- ours is in our own namespace.

**Comment by AndyDentFree** [comment]
Comment by @YordanYanakiev copied from #541 

> Just to note on "NottieBear" comment.
> I've just tested his solution - it does not fixing the issue for me.
> Practically I cant go release build since without linking my result app is nearly 60 MB for just a simple slide. It's a no-go situation :|
