### ISSUE TITLE
Add copyTo/copyFromRealm

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#661]
From [SO question](http://stackoverflow.com/questions/37999630/how-to-get-a-standalone-unmanaged-realmobject-using-realm-xamarin) basically requesting the equivalent of the Java [copyFromRealm](https://realm.io/docs/java/1.0.1/api/io/realm/Realm.html#copyFromRealm-E-) and [copyToRealmOrUpdate](https://realm.io/docs/java/1.0.1/api/io/realm/Realm.html#copyToRealmOrUpdate-E-)

Could loosely classify as _waiting for the user_ as I suggested possibly using different XAML binding techniques, to discourage people losing object liveliness.

**Comment by AndyDentFree** [comment]
User definitely wants this as has since lodged an issue (I closed as duplicate of this).

**Comment by j-hayes** [comment]
+1 on this for sure. 

Question about this. When this gets implemented will we be able to make changes to objects outside of a transaction? The pattern that I try to follow for data access this would be necessary. 

I am very unwilling to pass around Transaction objects in my viewmodel / view layer of my application. I'd much rather deal with unmanaged objects in write / update scenarios and remap down in my data layer to a managed object. While this may not be the most efficient way, not being coupled to a data access implementation is important to me.  

Having unmanaged objects would allow me to not have to duplicate my model classes one inheriting from realm object one not. But if that is what I have to do I'll deal.

**Comment by kristiandupont** [comment]
@j-hayes would #647 help in your situation? It will allow you to bind to realm objects without explicitly creating and committing transactions. Or is your situation different?

**Comment by AndyDentFree** [comment]
Waiting for #852 as it needs the schema in the standalone

**Comment by Harvinator** [comment]
Hi, does anyone have a workaround for this? (PCL)

I've tried using Json serialize/deserialize however getting a `null reference exception` which assume is due to #852 

All i really want is to store a static user RealmObject that my application requires frequently. What I'm having to do is pass around a realm instance through my function hierarchy and pull it out of Realm each time it's required. Ideally I want get the object once when the application launches as it will be required on every view.

**Comment by nirinchev** [comment]
Hi @Harvinator sorry for the delay, I must have missed your comment. Can you paste a stacktrace of the exception, as #852 shouldn't be an issue anymore.

**Comment by Harvinator** [comment]
I've just tried to reproduce the problem and it's working now! Unsure what I was doing differently before. Apologies for the false alarm

**Comment by AndyDentFree** [comment]
I have just encountered an excellent scenario showing exactly why this needs to become a higher priority issue.

App has a Pattern object with many Pixel children. They are building up the Pattern in memory as the user may not decide to Save.

Their Save code looks like this: 
```
public async Task SavePatternAsync(Pattern pattern)
{
   await _realm.WriteAsync(realm =>
   {
       realm.Add(pattern);
   });
}
```

They are getting an exception rom the UI thread:
_Essentially, the view that I've already left is trying to draw the pattern, while Realm is trying to save it at the same time_

Of course, the pattern argument they are passing in, is being adopted by the temporary thread in the `WriteAsync`.

What they need to be able to do is `CopyToRealm` so instead of an `Add` which adopts the pattern, it is copied. However, that also needs them to use `Find` on the result to get back an object on the local Realm.

**Comment by nirinchev** [comment]
I think it's better to guide them how to best fit their use-case to the Realm paradigms rather than trying to support every app scenario people can come up.

For example, in this case a much better approach would be to add a `bool IsConfirmed { get; set; }` property to their Pattern model and set that to true after saving. If the user decides not to save, they can delete the object. And if the app crashes or the user leaves to take a call and forgets about it, they can display a prompt at startup about finishing or discarding what they were doing last. Once they do that, they can work with managed objects only and there'll be no need to copy things around.

Alternatively, they can always use tools like automapper to copy the object before adding it to the Realm, so I can't see a reason for us to support that out of the box.

**Comment by AndyDentFree** [comment]
Further feedback from this user - this is a situation I can't see an easy workaround on. The approaches you mention above work for a single object but not a parent with bunch of children.

> 
> I realized an issue with the managed objects. Since I allow my users to select patterns they've previously made, make changes to them and then decide whether they want to save or discard said changes, I can't do this with managed objects, right?
> What I mean, my pattern/pixel properties are currently updating to the database, even if I haven't explicitly tapped the save button. I guess I'd need an unmanaged copy, then somehow replace the managed version with the new version.

**Comment by nirinchev** [comment]
It would work with children once we get cascading deletes, now it would just be annoying. But in their situation, it could be inapplicable indeed :/ Perhaps if they shared their complete model and briefly described how their app behaves, we could try to figure something out. 

How about keeping a transaction open until the user taps "save"? I know it's discouraged, especially with sync, but it might work for their case?

**Comment by AndyDentFree** [comment]
> It would work with children once we get cascading deletes

I don't see how. Cascading deletes will take out **all** children of an object. They want to be able to undo only _changes_ represented by adding **some** children, preserving others.

**Comment by JFMG** [comment]
Could I ask why this issue was closed? In the current project I am working in I'd like to have methods like copyFromRealm and copyToRealmOrUpdate.

I don't think it's intuitive that this code is causing an exception:
```cs
var myObject = await _myService.LoadMyObjectFromDbAsync();
myObject.Text = "Hello Realm";
await _myService.SaveMyObjectToDbAsync(myObject);
```
I'd like to use Realm like this because we separated the database logic from the view model logic to enable loose coupling. The only workaround I found was to serialize and deserialize my Realm object, like it's written in this StackOverflow post: https://stackoverflow.com/a/43999908/1584648

**Comment by nirinchev** [comment]
The issue was closed because we decided not to expose the copyFromRealm method as there are better third party tools for the job and writing a generic method to extract a standalone object from the database is a serious task that provides very little value.

We have added a method to add a standalone object to the database, so that direction has been covered.

The code snippet you posted provides very little information to be able to diagnose the reason for getting an exception, so please file a new issue with as much detail as possible and we'll investigate.

**Comment by pfedotovsky** [comment]
@vineetchoudhary I've improved your code a bit and pushed a NuGet package https://www.nuget.org/packages/Realm.Clone/

Source code: https://github.com/pfedotovsky/realm-dotnet-clone/blob/master/Realm.Clone/Realm.Clone/RealmExtensions.cs

**Comment by A9G-Data-Droid** [comment]
I'm trying to put a `RealmObject` in a SignalR pipe and it doesn't want to go, I'm getting an error:

> System.NotSupportedException: Realm.SyncSession is only valid for synchronized Realms (i.e. ones that are opened with FlexibleSyncConfiguration or PartitionSyncConfiguration). The unsupported member type is located on type 'Realms.Sync.Session'. 

I'm not trying to Sync anything. I'm not sure why `JsonConverter` or `SendHubMessage` are getting into sync code paths. I figured maybe it's because the object is managed and I need to unmanage it before I send it to somewhere else. 

That leads us here, where other languages have a [copyFromRealm](https://realm.io/docs/java/1.0.1/api/io/realm/Realm.html#copyFromRealm-E-) and .NET just doesn't. 

Why? because of 3rd party libraries that don't exist anymore?

**Comment by nirinchev** [comment]
I'm guessing that's because they don't respect the `[IgnoreDataMember]` annotation applied on the `IRealmObject.Realm` property. What you can do instead is use opt-in json serialization and annotate the members you explicitly want to make it into the json payload. Here are [the docs for Newtonsoft.Json](https://www.newtonsoft.com/json/help/html/JsonObjectAttributeOptIn.htm) but there are probably similar mechanisms for other json providers.

**Comment by A9G-Data-Droid** [comment]
Thanks for the insight @nirinchev but I don't have control over the json serialization methods used by SignalR. From what I can tell, `System.Text.Json.Serialization` doesn't support any Opt-In attributes I can leverage. There are numerous issues related to that topic that all end in a feature that is slated to be included in .NET8, where I am developing for 6...

Would forcing my object to become `unmanaged` fix this problem, and allow it to be serialized?

**Comment by A9G-Data-Droid** [comment]
Just to answer my own question: No. When I send an unmanaged object I get

> System.NotSupportedException: Using the dynamic API to access a RealmObject is only possible for managed (persisted) objects. The unsupported member type is located on type 'Realms.DynamicObjectApi'. Path: $.CustomerPart.Part.Customer.DynamicApi.
>  ---> System.NotSupportedException: Using the dynamic API to access a RealmObject is only possible for managed (persisted) objects.
>    at Realms.UnmanagedAccessor.get_DynamicApi()
>    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo

So I guess you can't send a Realm object through a SignalR pipe and maybe that's a separate issue.

**Comment by peppy** [comment]
One thing you can try is switching SignalR to use newtonsoft or messagepack quite easily. Both of these will give you opt-in support for properties.

https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson

https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Protocols.MessagePack/

You will need to make sure that these options suit your usage though. For instance, messagepack is the most efficient, but requires explicit opt in and has AOT considerations.

**Comment by nirinchev** [comment]
@A9G-Data-Droid I put up a PR that should allow you to customize the generated classes in order to apply the `JsonIgnore` attribute on the correct members. We're not doing this automatically today because we're targeting platforms lower than .net5, which means we can't be certain that our users have `System.Text.Json` built in. Once released, you would need to add

```
realm.custom_ignore_attribute = [System.Text.Json.Serialization.JsonIgnore]
```

to your global editorconfig, which will tell the Realm source generator to add the attribute to `Realm`, `Dynamic`, and a few other RealmObject properties which should be excluded from serialization.

**Comment by A9G-Data-Droid** [comment]
> You will need to make sure that these options suit your usage though. For instance, messagepack is the most efficient, but requires explicit opt in and has AOT considerations.

Wow! This is fantastic. This absolutely solved my specific problem. Thank you so much!
