### ISSUE TITLE
Add support to save List<T> to Blob where T is int, string

### ISSUE THREAD

**Issue by alexrainman** [realm/realm-dotnet#726]
> **Feature Request**:

With SQLite.Net-Extensions you can do something like this:

```
[TextBlob("profileIdsBlob")]
public List<int> profileIds { get; set; }
public string profileIdsBlob { get; set; }
```

This a big limitation. Im using SQLite because this is not supported in Realm.

**Comment by kristiandupont** [comment]
Properties that aren't automatic (i.e. implement a getter/setter) will be ignored by Realm so one way of achieving this is by implementing the property manually:
```csharp
public List<int> profileIds
{
    get { return Serializer.Deserialize(profileIdsBlob); }
    set { profileIdsBlob = Serializer.Serialize(value); }
}
```

This would require a class `Serializer` that implements the two static methods in your preferred way, like with `string.Join` and `string.Split` or something.

**Comment by nirinchev** [comment]
This will obviously not handle scenarios where you add or remove elements from the list, but those are also easily achievable with a custom List.

**Comment by alexrainman** [comment]
I already tried this but SET is not called when you populate realm from JSON so, the blob is never created and GET fails.

**Comment by alexrainman** [comment]
I also updates to 0.77 to get IList support but i get a Fody exception. I already created another thread for it.

**Comment by fealebenpae** [comment]
@alexrainman: this could work if the type of the property is an `IEnumerable<>` that you assign every time. Newtonsoft.Json will call the setter in this case as well.

**Comment by alexrainman** [comment]
It works. I believe this is something you can implement internally. Let's say i add [TextBlob] annotation. That means internally the field will be saved as a serialized object. That will be cool and will be make Realm even easier to use. Developers won't need custom Setters, neither a Serialization library and extra fields just to save a simple List<int>. That will be cool.

**Comment by fealebenpae** [comment]
I'm not sure we can handle this in a general fashion - there are several serialization schemes in .net and different values support different kinds of serialization libraries: BinaryFormatter, DataContractSerializer, various flavors of JSON. I don't believe we could implement such a feature robustly and still maintain cross-platform compatibility. What's more, I don't think it would be a good idea to add a serialization step because that kind of runs counter to the entire philosophy behind Realm.

However I think it would be terrific if you or someone else in the community interested in this feature authored a NuGet package that provides it, similarly to how `[TextBlob]` is provided by `SQLiteNetExtensions` which extends the base `sqlite-net` package.

**Comment by alexrainman** [comment]
I will think about it.
