### ISSUE TITLE
Document way to handle importing, as workaround for [ForeignKey] support

### ISSUE THREAD

**Issue by alexrainman** [realm/realm-dotnet#728]
> **Feature Request**: Just fill in the first two sections below.

It will be cool if i can set one-to-many relations using [ForeignKey] annotation. This will be really useful when you are parsing JSON to Realm.

In the real world you tie objects to their child by a key and not by an instance of the object itself.

**Comment by AndyDentFree** [comment]
> In the real world you tie objects to their child by a key
Is not quite that general - it is in only true in the relational world and Realm is **not** an ORM.

I can relate to the rationale behind the request because about 20 years ago I added _join relationships_ to my OOFILE C++ product, for exactly the same reason. However, the way that Realm works internally is truly as an object database, with some incredible optimisations for handling relationships.

So I am going to have a go at some sample code, possibly including an extension method, which provides a clean way of handling this situation.

**Comment by alexrainman** [comment]
I wish i can have an extension method to save a List<int> as serialized object, like SQLite.Net-Extensions does:

[TextBlob("myfieldBlob")]
public List<int> myfield { get; set; }
public string myfieldBlob { get; set; }

Anyway i will be waiting for your post. Thanks

**Comment by alexrainman** [comment]
Your example will be really useful for me!

**Comment by nirinchev** [comment]
You could achieve it by doing something like:
```csharp
[Ignored]
public int[] MyField
{
    get
    {
        return MyFieldBlob.Split(',').Select(int.Parse);
    }
    set
    {
        MyFieldBlob = string.Join(",", value);
    }
}

public string MyFieldBlob { get; set; }
```

If you're looking for extensions that help deserializing json objects into Realm, there's a 3rd party package that can help with that: https://github.com/sushihangover/Realm.Json.Extensions.
