### ISSUE TITLE
System.TypeInitializationException

### ISSUE THREAD

**Issue by amasasi** [realm/realm-dotnet#787]
> **Bugs**:  When i upgraded to realm 77.1 I got an error  System.TypeInitializationException: The type initializer for 'Realms.Realm' threw an exception.
as a result I reverted to 76.1  now realm 77.2 is out I upgraded but I  still get the same error. so I will stick with 76.1 until this gets resolved.

I can share a my project privately.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

System.TypeInitializationException: The type initializer for 'Realms.Realm' threw an exception. 

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```csharp

> Your code here. Bigger samples should ideally be as separate Xamarin/Visual Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?     77.1 & 77.2

Xamarin/Visual Studio version: ? 

Which operating system version and device: ?
 Windows 10 anniversaly update , VIsual studio 2014 update 2

**Comment by AndyDentFree** [comment]
More details on the exception might help but I think we probably need source to diagnose this further. Please send an attachment or link to help@realm.io

**Comment by amasasi** [comment]
I have sent a link to source

**Comment by AndyDentFree** [comment]
Crash replicated and being investigated further, with an Android build

**Comment by AndyDentFree** [comment]
A simnple fix seems to be just correcting the Supported ABIs setting.

On the project  `CDK.Mobile.Droid` Options - Build - Android Build - Advanced Tab.

The original sent to us had `armeabi` and `armeabi-v7a` checked but not `arm64-v8a`

We **do not support**  `armeabi` 

After removing it, I was able to run the app on one test device (Note II).

However, note that on my 64-bit ARM Device, a Galaxy Tab S2, 
I now get a `System.MissingMethodException` which I am not sure if it is looking for something in Realm code or is due to the cut-down example or third-party code. I suspect the latter and so am considering this issue closed pending further advice of a distinctly Realm problem.
