### ISSUE TITLE
Update object by PrimaryKey

### ISSUE THREAD

**Issue by kristiandupont** [realm/realm-dotnet#808]
Something functionally equivalent to the Java [copyToRealmOrUpdate](https://realm.io/docs/java/1.2.0/api/io/realm/Realm.html#copyToRealmOrUpdate-E-) or Swift's [add(object, true)](https://realm.io/docs/swift/1.0.2/api/Classes/Realm.html#/s:FC10RealmSwift5Realm3addFTCS_6Object6updateSb_T_)

**Comment by AndyDentFree** [comment]
Consider whilst naming and designing this, keeping consistency amongst PrimaryKey-based methods:

* potential change to add the overload `CreateObject(primaryKey)`
* not just passing in one object by primary key but also a future update on a `RealmResults` that might set a bunch of properties from a dictionary, or lambda, like a SQL `update` 
* adding an overload `RemoveForPrimaryKey` for efficient removal

This is related to #661 but is more constrained as it requires a PrimaryKey

**Comment by CrimsonKyle** [comment]
@AndyDentFree Is Realm Xamarin looking to support functionality similar to Realm Swift to allow updateing by Primary Key if Object with Primary Key Exists during a write transaction instead of throwing the current RealmDuplicatePrimaryKeyValueException just overwrite the object?
[https://realm.io/docs/swift/latest/#creating-and-updating-objects-with-primary-keys]
