### ISSUE TITLE
The type or namespace name 'PrimaryKey' could not be found

### ISSUE THREAD

**Issue by eman1986** [realm/realm-dotnet#823]
I'm using Realm 0.77.2 and I'm trying to set a  primary Key and according to the documentation (https://realm.io/docs/xamarin/latest/#primarykey-attributes) there should be an attribute but I get an error stating no such attribute exists.

I'm using VS2015 Update 3

**Comment by fealebenpae** [comment]
Hey @eman1986 - we've renamed our old `ObjectId` attribute to `PrimaryKey` in the `master` branch and the change will be reflected in our next release. I'm not sure why the change has leaked into our 0.77.2 docs, but you can use the [0.77.1 docs](https://realm.io/docs/xamarin/0.77.1/) because the API in 0.72.2 is the same.

/cc @AndyDentFree

**Comment by eman1986** [comment]
Thanks your response.
