### ISSUE TITLE
With Remotion.Linq we have too much duplicating dependencies

### ISSUE THREAD

**Issue by rudyryk** [realm/realm-dotnet#842]
The Realm is awesome, and the part of its awesomeness is that **it doesn't have many dependencies, it's totally self-contained**.

I've tried to update to 0.78, but now decided to roll back to 0.77.

This is crucial, I believe. The project size is **really** critical in Xamarin development for iOS because due to its specific compiled binaries are already just **huge** compared to native Objective C / Swift ones. And adding just some more megabites (tens of megabytes?) doesn't make it better.

Now I'm looking at [Remotion.Linq](https://www.nuget.org/packages/Remotion.Linq/) dependencies list. Well, Xamarin provides all of that already! So, now we'll just need to add **11 standard libs from Microsoft which replaces (?) Xamarin's ones**. Why?

I'd suggest to get rid of Remotion.Linq, seems like it's not designed against Xamarin.

**Comment by fealebenpae** [comment]
Hey @rudyryk,

Thank you for asking such an interesting question. The short answer is that those dependencies do not make it into your app at all and have zero effect on its size. To prove this, here is a screenshot from the output folder of a Xamarin.Forms app with Realm 0.78.1 installed:
![screenshot](https://cloud.githubusercontent.com/assets/289915/18608966/6c4c0b14-7cff-11e6-9be0-2b158c65638a.png)
You can perform the same experiment and verify this.

The long answer:
If you look closely at the dependencies list of Remotion.Linq, you'll notice that all of them are under the new .NET Standard profile. What this means, basically, is that Remotion.Linq declares a dependency on a number of core .NET features. The .NET Standard packages are a way to split the monolithic .NET Framework into logical pieces - the packages Remotion.Linq depends on contain only reference assemblies which formally describe .NET APIs, they do not have any implementation. Xamarin already implements .NET Standard 1.6 and already provides implementations for these packages, which is why their assemblies never make it into the final Xamarin app. You can read more about Xamarin's support for .NET Standard [here](https://blog.xamarin.com/net-standard-library-support-for-xamarin).

This verbose way of declaring dependencies is actually a boon to applications that embed the .NET Framework such as Xamarin - if all the libraries your app uses declare .NET Standard dependencies, it would be very easy for Xamarin to compile away those parts of the Xamarin implementation of the .NET Framework that your app doesn't need without an error-prone static analysis process. I believe this should make it possible to reduce the size of Xamarin apps even further once the majority of tools and libraries in the ecosystem has transitioned to .NET Standard.

Realm is designed to operate in compact embedded environments at peak efficiency. Dragging along tens of megabytes' worth of dependencies would go counter to one of the most important Realm design principles. If you notice anything else that brings concerns over speed and size, please let us know right away.

**Comment by rudyryk** [comment]
@fealebenpae I see, thank you for the clarification!

**Comment by rudyryk** [comment]
BTW, when added libs from Microsoft we are forced to accept their license agreement. Although at first glance I don't see any problems, but I'm not a lawyer :) And I see it as a factor of risk to use libs with license other than traditional BSD / MIT / Apache.
