### ISSUE TITLE
Crash if try to use schema from standalone

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#852]
Our `RealmObject.ObjectSchema`` will cause a null-reference exception if the object is standalone.

This discovery whilst working on #661 may explain some user crashes.

**Comment by AndyDentFree** [comment]
Design-wise there are some interesting tradeoffs.

Currently the Schema is supplied by being owned by the Metadata object, which is linked when a RealmObject becomes Managed.

The Metadata object is owned and supplied by the Realm (and is a controversial structure including column indices (it is likely to be re-designed as part of sync).

## Tradeoffs:

We don't really want to add another pointer into RealmObject that points independently to the ObjectSchema.

I think it is desirable to cache the schema when generated, rather than looking it up each time. I think this can be cached in a static pointer.

**Comment by fealebenpae** [comment]
Let's weave a static field on every `RealmObject` descendant so that:
```csharp
class Person : RealmObject
{
    private static readonly ObjectSchema _realmSchema;

    static Person()
    {
        _realmSchema = ObjectSchema.FromType(typeof(Person));
    }

    public Person()
    {
        base.ObjectSchema = Person._realmSchema;
    }
}
```

This means that `RealmObject.ObjectSchema` becomes 
```csharp
public Schema.ObjectSchema ObjectSchema { get; protected set; }
```

We should then change the logic inside the `Realm` constructor to pull out the `_realmSchema` field for every type instead of generating the schema with reflection each time, which would also yield a minor performance improvement on every `Realm.GetInstance()`.

Thus every type would be the authoritative owner of its schema instead of its `RealmObject.Metadata` structure.

**Comment by nirinchev** [comment]
As far as I can tell, `ObjectSchema` returns null if the object is standalone and doesn't cause a NRE. Do you feel we should still go for the proposed weaver solution?

**Comment by AndyDentFree** [comment]
My original 👍 still stands - yes I like the weaver idea.
