### ISSUE TITLE
Multiple Records with `PrimaryKey` set to `null`

### ISSUE THREAD

**Issue by sushihangover** [realm/realm-dotnet#999]
#### Goal

Adding multiple records without setting PK should throw exception

#### Expected Results

`Realms.RealmDuplicatePrimaryKeyValueException`

#### Actual Results

Successful Commit, 3 records added

#### Steps & Code to Reproduce

```
public class KeyValueRO : RealmObject
{
	[PrimaryKey]
	public string Key { get; set; }
	public string Value { get; set; }
}

using (var r = Realm.GetInstance("foo.db"))
{
	r.Write(() =>
	{
		var obj = r.CreateObject<KeyValueRO>();
		var obj2 = r.CreateObject<KeyValueRO>();
		var obj3 = r.CreateObject<KeyValueRO>();
        });
	System.Diagnostics.Debug.WriteLine(r.All<KeyValueRO>().Count()); 
        // Count = 3;
}    
using (var r = Realm.GetInstance("foo2.db"))
{
	r.Write(() =>
	{
		var obj1 = new KeyValueRO();
		r.Manage(obj1);
		var obj2 = new KeyValueRO();
		r.Manage(obj2);
		var obj3 = new KeyValueRO();
		r.Manage(obj3);
	});
	System.Diagnostics.Debug.WriteLine(r.All<KeyValueRO>().Count()); 
        // Count = 3
}      
 
```
#### Version of Realm and tooling

Realm version(s): v0.80.0

**Comment by nirinchev** [comment]
Hi @sushihangover, thank you for the report. We are planning to deprecate `CreateObject` (#998), so my advice would be to start using `Realm.Add` (the renamed version of `Realm.Manage`). 

The reason why your code doesn't behave as expected is that your primary key is null - the default value for string and we erroneously skipped setting those, which circumvented our validations - if you set a non-null value for your PK, you should get the exception. Long story short, it's fixed in #990 and if it's urgent, feel free to grab the nuget from the CI build. Otherwise, we're gearing up for a release before the holidays that will contain the fix.

**Comment by sushihangover** [comment]
@nirinchev Thanks for info... 

BTW: I did not think that your CI builds are public

#807 and #601 cross reference themselves and both were closed.

![screen shot 2016-12-14 at 9 53 07 am](https://cloud.githubusercontent.com/assets/1294194/21194011/2dee958e-c1e3-11e6-8b56-5f1cbfbbfa6a.png)

FYI: I build from source so I can cherrypick non-released fixes/enhancements (which is a pain since 90% of the time the c++ code fails to build due to missing/mismatched files... but that is a different issue)

**Comment by nirinchev** [comment]
Oh... I am sorry, I assumed the CI was public, but couldn't really verify that. @fealebenpae is working on reviving the nightlies.
